/**
 * G1 MART — Pilot Catalogue (50 Items)
 * Strict Section 9.2 Compliance:
 * - Approved-only image rendering (storefront displays official placeholder)
 * - Zero stock photo guessing
 * - Ambiguous names flagged for store review
 * - Unconfirmed prices left as TBA (priceConfirmed: false)
 */
import type { Product } from '@/types';

export const CATALOG_PRODUCTS: Product[] = [
  {
    "id": "g1-1",
    "itemNumber": 1,
    "rawName": "5 MUCH",
    "name": "5 Much",
    "brand": "Unverified Brand",
    "category": "snacks",
    "subCategory": "Chocolates & Sweets",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 18,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Ambiguous name in POS. Brand and product variant not stated. Placeholder assigned.",
    "description": "Item from G1 Mart inventory awaiting product details verification.",
    "rating": 4.8,
    "reviewsCount": 15,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Brand and specific candy/wafer variant unspecified in POS report."
  },
  {
    "id": "g1-2",
    "itemNumber": 2,
    "rawName": "5 STAR 5RS",
    "name": "Cadbury 5 Star Chocolate Bar (₹5 Pack)",
    "brand": "Cadbury",
    "category": "snacks",
    "subCategory": "Chocolates & Sweets",
    "unit": "1 piece",
    "price": 5,
    "priceConfirmed": true,
    "originalPrice": 5,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 15,
    "image": "/products/placeholder.svg",
    "image_path": "/products/prod-42.jpg",
    "image_source": "manufacturer",
    "image_license": "Proprietary Brand Pack",
    "image_status": "pending",
    "image_match_note": "Candidate pack image matches Cadbury 5 Star ₹5 bar. Awaiting user approval in contact sheet.",
    "description": "Classic smooth caramel and nougat chocolate bar.",
    "rating": 4.8,
    "reviewsCount": 16,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-3",
    "itemNumber": 3,
    "rawName": "5 Star Tea 250g",
    "name": "5 Star Tea (250 g)",
    "brand": "5 Star Tea",
    "category": "beverages",
    "subCategory": "Tea & Chai",
    "unit": "250 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 15,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Regional brand pack. No approved photo in /product-photos-raw/. Placeholder assigned.",
    "description": "Regional leaf tea powder pack.",
    "rating": 4.8,
    "reviewsCount": 17,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Regional tea pack. Needs exact package photo from store."
  },
  {
    "id": "g1-4",
    "itemNumber": 4,
    "rawName": "50-50 SWEET&SALTY",
    "name": "Britannia 50-50 Sweet & Salty Biscuits",
    "brand": "Britannia",
    "category": "snacks",
    "subCategory": "Biscuits & Cookies",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size unstated in POS. Placeholder assigned.",
    "description": "Light and crispy sweet & salty biscuits.",
    "rating": 4.8,
    "reviewsCount": 18,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight missing in POS (could be 45g, 65g, or 120g)."
  },
  {
    "id": "g1-5",
    "itemNumber": 5,
    "rawName": "707 SOAP",
    "name": "707 Soap Bar",
    "brand": "707",
    "category": "household",
    "subCategory": "Detergent & Fabric Care",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Ambiguous entry. Laundry soap or bath bar not specified. Placeholder assigned.",
    "description": "Soap bar from G1 Mart inventory.",
    "rating": 4.8,
    "reviewsCount": 19,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Ambiguous soap type and weight."
  },
  {
    "id": "g1-6",
    "itemNumber": 6,
    "rawName": "AACHHI GARAM MASALA",
    "name": "Aachi Garam Masala Powder",
    "brand": "Aachi",
    "category": "edible-oils",
    "subCategory": "Spices & Masalas",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack weight missing in POS. Placeholder assigned.",
    "description": "Aromatic blend of ground Indian spices.",
    "rating": 4.8,
    "reviewsCount": 20,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight not specified (50g vs 100g)."
  },
  {
    "id": "g1-7",
    "itemNumber": 7,
    "rawName": "AACHI APPALAM 100G",
    "name": "Aachi Appalam (100 g)",
    "brand": "Aachi",
    "category": "snacks",
    "subCategory": "Papads & Fryums",
    "unit": "100 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Exact pack size known. Awaiting photo in /product-photos-raw/.",
    "description": "Crispy South Indian style appalam.",
    "rating": 4.8,
    "reviewsCount": 21,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-8",
    "itemNumber": 8,
    "rawName": "AACHI CHICKEN MASALA",
    "name": "Aachi Chicken Masala Powder",
    "brand": "Aachi",
    "category": "edible-oils",
    "subCategory": "Spices & Masalas",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack weight missing in POS.",
    "description": "Traditional spice mix for chicken curries.",
    "rating": 4.8,
    "reviewsCount": 22,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight missing."
  },
  {
    "id": "g1-9",
    "itemNumber": 9,
    "rawName": "Aashirvaad 1kg",
    "name": "Aashirvaad 1kg (Variant Unspecified)",
    "brand": "Aashirvaad",
    "category": "rice-dal-atta",
    "subCategory": "Atta & Flours",
    "unit": "1 kg",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 33,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Ambiguous variant. Could be Whole Wheat Atta, Multi-grain, or Salt. Placeholder enforced.",
    "description": "1kg pack from Aashirvaad.",
    "rating": 4.8,
    "reviewsCount": 23,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Variant not specified (Atta vs Salt vs Flours)."
  },
  {
    "id": "g1-10",
    "itemNumber": 10,
    "rawName": "AASHIRVAAD CRYSTAL SALT 1KG",
    "name": "Aashirvaad Crystal Salt (1 kg)",
    "brand": "Aashirvaad",
    "category": "rice-dal-atta",
    "subCategory": "Salt & Sugar",
    "unit": "1 kg",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 15,
    "image": "/products/placeholder.svg",
    "image_path": "/products/prod-1.jpg",
    "image_source": "manufacturer",
    "image_license": "Proprietary Brand Pack",
    "image_status": "pending",
    "image_match_note": "Candidate photo matches Aashirvaad salt pack. Pending user review.",
    "description": "Pure solar-evaporated crystal salt.",
    "rating": 4.8,
    "reviewsCount": 24,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-11",
    "itemNumber": 11,
    "rawName": "AASHIRVAAD SALT",
    "name": "Aashirvaad Iodised Salt",
    "brand": "Aashirvaad",
    "category": "rice-dal-atta",
    "subCategory": "Salt & Sugar",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 12,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size missing in POS.",
    "description": "Refined iodised salt.",
    "rating": 4.8,
    "reviewsCount": 25,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack size missing in POS entry."
  },
  {
    "id": "g1-12",
    "itemNumber": 12,
    "rawName": "Aashirvaad Suji Rava",
    "name": "Aashirvaad Suji Rava",
    "brand": "Aashirvaad",
    "category": "rice-dal-atta",
    "subCategory": "Atta & Flours",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 21,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size missing in POS.",
    "description": "Finely milled semolina suji rava.",
    "rating": 4.8,
    "reviewsCount": 26,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight (500g or 1kg) missing in POS."
  },
  {
    "id": "g1-13",
    "itemNumber": 13,
    "rawName": "Aashirvaad Vermicelli",
    "name": "Aashirvaad Vermicelli",
    "brand": "Aashirvaad",
    "category": "rice-dal-atta",
    "subCategory": "Rice & Grains",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size missing in POS.",
    "description": "Wheat vermicelli for upma and payasam.",
    "rating": 4.8,
    "reviewsCount": 27,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight missing."
  },
  {
    "id": "g1-14",
    "itemNumber": 14,
    "rawName": "AASHIRVAAD VERMICELLI 850G",
    "name": "Aashirvaad Roasted Vermicelli (850 g)",
    "brand": "Aashirvaad",
    "category": "rice-dal-atta",
    "subCategory": "Rice & Grains",
    "unit": "850 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Exact weight known. Awaiting photo in /product-photos-raw/.",
    "description": "Pre-roasted vermicelli pack.",
    "rating": 4.8,
    "reviewsCount": 28,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-15",
    "itemNumber": 15,
    "rawName": "ACID 700ML",
    "name": "Cleaning Muriatic Acid (700 ml)",
    "brand": "Unstated",
    "category": "household",
    "subCategory": "Floor & Cleaners",
    "unit": "700 ml",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Generic cleaning acid. Brand unstated.",
    "description": "Heavy duty toilet and floor cleaning acid.",
    "rating": 4.8,
    "reviewsCount": 29,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Manufacturer/brand unstated."
  },
  {
    "id": "g1-16",
    "itemNumber": 16,
    "rawName": "Ajay Brush",
    "name": "Ajay Toothbrush",
    "brand": "Ajay",
    "category": "personal-care",
    "subCategory": "Oral Care",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 12,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Specific variant unstated.",
    "description": "Manual toothbrush with round end bristles.",
    "rating": 4.8,
    "reviewsCount": 30,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Bristle variant (Medium / Soft / Hard) not stated."
  },
  {
    "id": "g1-17",
    "itemNumber": 17,
    "rawName": "ALL IN ONE 100G",
    "name": "All In One (100 g)",
    "brand": "Unstated",
    "category": "household",
    "subCategory": "Home Utilities & Stationery",
    "unit": "100 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Cryptic cashier name. Product identity unverified.",
    "description": "Product from G1 Mart inventory.",
    "rating": 4.8,
    "reviewsCount": 31,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Cryptic entry: could be namkeen mixture, spice blend, or home cleaning powder."
  },
  {
    "id": "g1-18",
    "itemNumber": 18,
    "rawName": "ALLOUT MATCHS",
    "name": "Allout / Matches Entry",
    "brand": "Unstated",
    "category": "household",
    "subCategory": "Home Utilities & Stationery",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Conflicting cashier entry. Placeholder assigned.",
    "description": "Item from G1 Mart inventory.",
    "rating": 4.8,
    "reviewsCount": 32,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Conflicting entry: combines 'Allout' (mosquito repellent) with 'MATCHS'."
  },
  {
    "id": "g1-19",
    "itemNumber": 19,
    "rawName": "APSARA PENCILS",
    "name": "Apsara Platinum Extra Dark Pencils",
    "brand": "Apsara",
    "category": "household",
    "subCategory": "Home Utilities & Stationery",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Awaiting photo upload into /product-photos-raw/.",
    "description": "High quality dark writing pencils pack.",
    "rating": 4.8,
    "reviewsCount": 33,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-20",
    "itemNumber": 20,
    "rawName": "ARIEL FRONT LIQ 10",
    "name": "Ariel Matic Front Load Liquid Detergent (₹10 Sachet)",
    "brand": "Ariel",
    "category": "household",
    "subCategory": "Detergent & Fabric Care",
    "unit": "1 piece",
    "price": 10,
    "priceConfirmed": true,
    "originalPrice": 10,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 48,
    "image": "/products/placeholder.svg",
    "image_path": "/products/prod-9.jpg",
    "image_source": "manufacturer",
    "image_license": "Proprietary Brand Pack",
    "image_status": "pending",
    "image_match_note": "Candidate pack image matches Ariel Matic Front Load pack. Pending user review.",
    "description": "Liquid detergent sachet formulated for front load washing machines.",
    "rating": 4.8,
    "reviewsCount": 34,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-21",
    "itemNumber": 21,
    "rawName": "Ariel Power Gel Top Load&semi Auto 1kg",
    "name": "Ariel Matic Power Gel Top Load & Semi-Auto (1 kg)",
    "brand": "Ariel",
    "category": "household",
    "subCategory": "Detergent & Fabric Care",
    "unit": "1 kg",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Exact bottle photo not in /product-photos-raw/.",
    "description": "Tough stain removal gel for top load machines.",
    "rating": 4.8,
    "reviewsCount": 35,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-22",
    "itemNumber": 22,
    "rawName": "AROKYA MILK",
    "name": "Arokya Fresh Toned Milk Pouch",
    "brand": "Arokya",
    "category": "dairy-bakery",
    "subCategory": "Milk & Curd",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack volume missing in POS.",
    "description": "Pasteurised toned milk from Arokya.",
    "rating": 4.8,
    "reviewsCount": 36,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pouch size (500ml vs 1L) unstated."
  },
  {
    "id": "g1-23",
    "itemNumber": 23,
    "rawName": "ARUN BITES",
    "name": "Arun Icecream Bites",
    "brand": "Arun Icecreams",
    "category": "dairy-bakery",
    "subCategory": "Ice Creams & Frozen Treats",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 63,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Zero guessing: placeholder enforced until exact wrapper photo uploaded.",
    "description": "Bite-sized chocolate coated ice cream treat.",
    "rating": 4.8,
    "reviewsCount": 37,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-24",
    "itemNumber": 24,
    "rawName": "ARUN DONUT",
    "name": "Arun Icecream Donut Bar",
    "brand": "Arun Icecreams",
    "category": "dairy-bakery",
    "subCategory": "Ice Creams & Frozen Treats",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 60,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Placeholder enforced.",
    "description": "Donut shaped novelty ice cream bar.",
    "rating": 4.8,
    "reviewsCount": 38,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-25",
    "itemNumber": 25,
    "rawName": "ARUN DOUBLE",
    "name": "Arun Icecream Double Bar",
    "brand": "Arun Icecreams",
    "category": "dairy-bakery",
    "subCategory": "Ice Creams & Frozen Treats",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Placeholder enforced.",
    "description": "Twin flavoured ice cream bar.",
    "rating": 4.8,
    "reviewsCount": 39,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-26",
    "itemNumber": 26,
    "rawName": "ARUN IBAR",
    "name": "Arun Icecream i-Bar Stick",
    "brand": "Arun Icecreams",
    "category": "dairy-bakery",
    "subCategory": "Ice Creams & Frozen Treats",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Placeholder enforced.",
    "description": "Premium ice cream stick bar.",
    "rating": 4.8,
    "reviewsCount": 40,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-27",
    "itemNumber": 27,
    "rawName": "ARUN MILKY FANTASY",
    "name": "Arun Icecream Milky Fantasy Stick",
    "brand": "Arun Icecreams",
    "category": "dairy-bakery",
    "subCategory": "Ice Creams & Frozen Treats",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Placeholder enforced.",
    "description": "Rich milky white ice cream stick bar.",
    "rating": 4.8,
    "reviewsCount": 41,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-28",
    "itemNumber": 28,
    "rawName": "Arun Popitos",
    "name": "Arun Icecream Popitos",
    "brand": "Arun Icecreams",
    "category": "dairy-bakery",
    "subCategory": "Ice Creams & Frozen Treats",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 18,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Placeholder enforced.",
    "description": "Mini ice cream pop treat.",
    "rating": 4.8,
    "reviewsCount": 42,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-29",
    "itemNumber": 29,
    "rawName": "Arun Sunny Sil",
    "name": "Arun Icecream Sunny Slice / Silver",
    "brand": "Arun Icecreams",
    "category": "dairy-bakery",
    "subCategory": "Ice Creams & Frozen Treats",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Abbreviated entry in POS. Placeholder enforced.",
    "description": "Ice cream slice treat.",
    "rating": 4.8,
    "reviewsCount": 43,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Abbreviated variant 'Sunny Sil' in POS report."
  },
  {
    "id": "g1-30",
    "itemNumber": 30,
    "rawName": "ARUN TOFFEE CON",
    "name": "Arun Icecream Toffee Cone",
    "brand": "Arun Icecreams",
    "category": "dairy-bakery",
    "subCategory": "Ice Creams & Frozen Treats",
    "unit": "1 piece",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 18,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Placeholder enforced.",
    "description": "Crispy waffle cone filled with toffee ice cream.",
    "rating": 4.8,
    "reviewsCount": 44,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-31",
    "itemNumber": 31,
    "rawName": "ASSORATED FRUIT",
    "name": "Assorted Fruit Item",
    "brand": "Unstated",
    "category": "fruits-vegetables",
    "subCategory": "Fresh Produce & Fruits",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Highly ambiguous product identity. Placeholder assigned.",
    "description": "Product from G1 Mart inventory.",
    "rating": 4.8,
    "reviewsCount": 45,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Ambiguous entry: could be confectionery fruit chews, fruit jam, or fresh fruits."
  },
  {
    "id": "g1-32",
    "itemNumber": 32,
    "rawName": "Avalu 250g",
    "name": "Mustard Seeds / Avalu (250 g)",
    "brand": "G1 Mart Store-Packed",
    "category": "edible-oils",
    "subCategory": "Whole Spices & Seeds",
    "unit": "250 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Store-packed grain. Awaiting physical pack photo upload.",
    "description": "Clean black mustard seeds (avalu).",
    "rating": 4.8,
    "reviewsCount": 46,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-33",
    "itemNumber": 33,
    "rawName": "Avalu50g",
    "name": "Mustard Seeds / Avalu (50 g)",
    "brand": "G1 Mart Store-Packed",
    "category": "edible-oils",
    "subCategory": "Whole Spices & Seeds",
    "unit": "50 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Store-packed grain. Awaiting photo.",
    "description": "Clean black mustard seeds (avalu).",
    "rating": 4.8,
    "reviewsCount": 47,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-34",
    "itemNumber": 34,
    "rawName": "BADAM 100GR",
    "name": "Whole Almonds / Badam (100 g)",
    "brand": "G1 Mart Store-Packed",
    "category": "snacks",
    "subCategory": "Dry Fruits & Nuts",
    "unit": "100 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Store-packed dry fruit. Awaiting photo in /product-photos-raw/.",
    "description": "Premium California whole almonds.",
    "rating": 4.8,
    "reviewsCount": 48,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-35",
    "itemNumber": 35,
    "rawName": "BADAM 250G",
    "name": "Whole Almonds / Badam (250 g)",
    "brand": "G1 Mart Store-Packed",
    "category": "snacks",
    "subCategory": "Dry Fruits & Nuts",
    "unit": "250 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Store-packed dry fruit. Awaiting photo in /product-photos-raw/.",
    "description": "Premium California whole almonds.",
    "rating": 4.8,
    "reviewsCount": 49,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-36",
    "itemNumber": 36,
    "rawName": "BADAM 50G",
    "name": "Whole Almonds / Badam (50 g)",
    "brand": "G1 Mart Store-Packed",
    "category": "snacks",
    "subCategory": "Dry Fruits & Nuts",
    "unit": "50 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Store-packed dry fruit. Awaiting photo in /product-photos-raw/.",
    "description": "Premium California whole almonds.",
    "rating": 4.8,
    "reviewsCount": 50,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-37",
    "itemNumber": 37,
    "rawName": "BAMBINO MYSORE PACK 200G",
    "name": "Bambino Mysore Pak Sweet Box (200 g)",
    "brand": "Bambino",
    "category": "snacks",
    "subCategory": "Chocolates & Sweets",
    "unit": "200 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Sweet box photo not in /product-photos-raw/.",
    "description": "Traditional melt-in-mouth Mysore Pak sweet box.",
    "rating": 4.8,
    "reviewsCount": 51,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-38",
    "itemNumber": 38,
    "rawName": "BAMBINON VERMICELLI 250G",
    "name": "Bambino Roasted Vermicelli (250 g)",
    "brand": "Bambino",
    "category": "rice-dal-atta",
    "subCategory": "Rice & Grains",
    "unit": "250 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack photo not in /product-photos-raw/.",
    "description": "Pre-roasted short cut vermicelli.",
    "rating": 4.8,
    "reviewsCount": 52,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-39",
    "itemNumber": 39,
    "rawName": "BANSI RAVA 500G",
    "name": "Bansi Rava (500 g)",
    "brand": "G1 Mart Store-Packed",
    "category": "rice-dal-atta",
    "subCategory": "Atta & Flours",
    "unit": "500 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Store-packed staple. Awaiting pack photo.",
    "description": "Coarsely ground whole wheat bansi rava.",
    "rating": 4.8,
    "reviewsCount": 53,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-40",
    "itemNumber": 40,
    "rawName": "BAT PAPAD 250G",
    "name": "Bat Papad (250 g)",
    "brand": "Unstated",
    "category": "snacks",
    "subCategory": "Papads & Fryums",
    "unit": "250 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Brand unstated.",
    "description": "Bat shaped crispy fryums / papad.",
    "rating": 4.8,
    "reviewsCount": 54,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Manufacturer/brand unstated."
  },
  {
    "id": "g1-41",
    "itemNumber": 41,
    "rawName": "BINGO CHILLI",
    "name": "Bingo Mad Angles Chilli Sprinkles",
    "brand": "Bingo",
    "category": "snacks",
    "subCategory": "Chips & Namkeen",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 36,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size unstated in POS.",
    "description": "Crunchy triangle chips with spicy chilli seasoning.",
    "rating": 4.8,
    "reviewsCount": 55,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight unstated in POS."
  },
  {
    "id": "g1-42",
    "itemNumber": 42,
    "rawName": "BINGO KOREAN",
    "name": "Bingo Korean Spicy Potato Chips",
    "brand": "Bingo",
    "category": "snacks",
    "subCategory": "Chips & Namkeen",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size unstated in POS.",
    "description": "Spicy Korean style potato chips.",
    "rating": 4.8,
    "reviewsCount": 56,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight unstated in POS."
  },
  {
    "id": "g1-43",
    "itemNumber": 43,
    "rawName": "BINGO MASALA",
    "name": "Bingo Mad Angles Masala Madness",
    "brand": "Bingo",
    "category": "snacks",
    "subCategory": "Chips & Namkeen",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 15,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size unstated in POS.",
    "description": "Crunchy triangle chips with chatpata masala flavour.",
    "rating": 4.8,
    "reviewsCount": 57,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight unstated in POS."
  },
  {
    "id": "g1-44",
    "itemNumber": 44,
    "rawName": "BINGO MASTI",
    "name": "Bingo Tedhe Medhe Masala Tadka / Masti",
    "brand": "Bingo",
    "category": "snacks",
    "subCategory": "Chips & Namkeen",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 15,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size unstated in POS.",
    "description": "Spicy curved corn snack sticks.",
    "rating": 4.8,
    "reviewsCount": 58,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight unstated in POS."
  },
  {
    "id": "g1-45",
    "itemNumber": 45,
    "rawName": "BINGO TOMATO",
    "name": "Bingo Mad Angles Tomato Madness",
    "brand": "Bingo",
    "category": "snacks",
    "subCategory": "Chips & Namkeen",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size unstated in POS.",
    "description": "Tangy tomato flavoured triangle chips.",
    "rating": 4.8,
    "reviewsCount": 59,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight unstated in POS."
  },
  {
    "id": "g1-46",
    "itemNumber": 46,
    "rawName": "BINO TEMATO 21G",
    "name": "Bingo Mad Angles Tomato Madness (21 g)",
    "brand": "Bingo",
    "category": "snacks",
    "subCategory": "Chips & Namkeen",
    "unit": "21 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 21,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Exact 21g pack known. Awaiting photo in /product-photos-raw/.",
    "description": "Tangy tomato flavoured triangle chips (21 g pocket pack).",
    "rating": 4.8,
    "reviewsCount": 60,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-47",
    "itemNumber": 47,
    "rawName": "Biriyani Masala",
    "name": "Biryani Masala Powder",
    "brand": "Unstated",
    "category": "edible-oils",
    "subCategory": "Spices & Masalas",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Brand and pack size both missing. Flagged for review.",
    "description": "Aromatic biryani masala powder.",
    "rating": 4.8,
    "reviewsCount": 61,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Brand and pack weight both missing in POS record."
  },
  {
    "id": "g1-48",
    "itemNumber": 48,
    "rawName": "BISCOTT",
    "name": "Biscotti / Biscuit Item",
    "brand": "Unstated",
    "category": "snacks",
    "subCategory": "Biscuits & Cookies",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Cryptic cashier abbreviation. Product identity unverified.",
    "description": "Item from G1 Mart inventory.",
    "rating": 4.8,
    "reviewsCount": 62,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Cryptic cashier abbreviation 'BISCOTT'. Brand and pack unspecified."
  },
  {
    "id": "g1-49",
    "itemNumber": 49,
    "rawName": "BLEACHUNG POWDER 100G",
    "name": "Disinfectant Bleaching Powder (100 g)",
    "brand": "G1 Mart Store-Packed",
    "category": "household",
    "subCategory": "Floor & Cleaners",
    "unit": "100 g",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 10,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Store-packed disinfectant. Awaiting physical pack photo.",
    "description": "Household sanitation and water disinfectant bleaching powder.",
    "rating": 4.8,
    "reviewsCount": 63,
    "isPopular": false,
    "isBestDeal": false,
    "is_ambiguous": false
  },
  {
    "id": "g1-50",
    "itemNumber": 50,
    "rawName": "BOOST",
    "name": "Boost Chocolate Health Drink",
    "brand": "Boost",
    "category": "beverages",
    "subCategory": "Health Drinks",
    "unit": "1 pack",
    "price": 0,
    "priceConfirmed": false,
    "originalPrice": 0,
    "discountPercentage": 0,
    "inStock": true,
    "stockCount": 93,
    "image": "/products/placeholder.svg",
    "image_source": "placeholder",
    "image_license": null,
    "image_status": "placeholder",
    "image_match_note": "Pack size unstated in POS.",
    "description": "Malted chocolate nutritional drink mix.",
    "rating": 4.8,
    "reviewsCount": 64,
    "isPopular": true,
    "isBestDeal": false,
    "is_ambiguous": true,
    "ambiguity_note": "Pack weight unstated (could be 200g, 500g, or 1kg)."
  }
];
