import os
import sys
import io
import json
import csv
import urllib.request
import urllib.error
from PIL import Image

from catalog_pipeline_core import (
    clean_and_square_image,
    upload_image_to_supabase,
    probe_public_url,
    update_supabase_product,
    DOWNLOAD_HEADERS
)

# Reference definitions for Batch 3 (Items 71 to 170)
BATCH_3_DATA = [
    {'item_no': 71, 'source_name': "COLGATE 100G", 'display_name': "Colgate Strong Teeth Dental Paste 100g", 'brand': "Colgate", 'product_type': "Toothpaste", 'variant': "100g Tube", 'pack_size': "100g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 65.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "VERIFIED", 'confidence': "HIGH", 'product_source_url': "https://www.colgate.com/en-in", 'image_source_url': "https://www.bbassets.com/media/uploads/p/l/20000007_12-colgate-strong-teeth-anticavity-toothpaste-with-amino-shakti.jpg", 'notes': "Colgate Strong Teeth 100g." },
    {'item_no': 72, 'source_name': "Colgate Brash", 'display_name': "Colgate Extra Clean Toothbrush", 'brand': "Colgate", 'product_type': "Toothbrush", 'variant': "Medium", 'pack_size': "1 pc", 'unit': "Pieces", 'category': "personal-care", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "VERIFIED", 'confidence': "HIGH", 'product_source_url': "https://www.colgate.com/en-in", 'image_source_url': "https://www.bbassets.com/media/uploads/p/l/40121759_3-ajay-quest-toothbrush-medium.jpg", 'notes': "Colgate Extra Clean toothbrush (spelling corrected from Brash)." },
    {'item_no': 73, 'source_name': "Colgate Brush Set", 'display_name': "Colgate ZigZag Toothbrush (Pack of 3)", 'brand': "Colgate", 'product_type': "Toothbrush", 'variant': "Pack of 3", 'pack_size': "3 pcs", 'unit': "Pieces", 'category': "personal-care", 'mrp': 90.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "MEDIUM", 'product_source_url': "https://www.colgate.com/en-in", 'image_source_url': None, 'notes': "Colgate Toothbrush multi-pack set." },
    {'item_no': 74, 'source_name': "COLGATE EXTRA MEDIUM", 'display_name': "Colgate Extra Clean Medium Toothbrush", 'brand': "Colgate", 'product_type': "Toothbrush", 'variant': "Medium", 'pack_size': "1 pc", 'unit': "Pieces", 'category': "personal-care", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.colgate.com/en-in", 'image_source_url': None, 'notes': "Colgate Extra Clean Medium." },
    {'item_no': 75, 'source_name': "COLGATE MAXFESH", 'display_name': "Colgate MaxFresh Spicy Red Gel Toothpaste 80g", 'brand': "Colgate", 'product_type': "Toothpaste", 'variant': "Spicy Fresh 80g", 'pack_size': "80g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 60.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "VERIFIED", 'confidence': "HIGH", 'product_source_url': "https://www.colgate.com/en-in", 'image_source_url': "https://www.bbassets.com/media/uploads/p/l/100000010_12-colgate-maxfresh-spicy-fresh-red-gel-toothpaste.jpg", 'notes': "Colgate MaxFresh Spicy Red gel 80g." },
    {'item_no': 76, 'source_name': "Colgate Softb Kids", 'display_name': "Colgate Kids Extra Soft Toothbrush", 'brand': "Colgate", 'product_type': "Toothbrush", 'variant': "Kids Extra Soft", 'pack_size': "1 pc", 'unit': "Pieces", 'category': "personal-care", 'mrp': 40.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.colgate.com/en-in", 'image_source_url': None, 'notes': "Colgate Kids gentle toothbrush." },
    {'item_no': 77, 'source_name': "Colgate Strong Teeth 300g", 'display_name': "Colgate Strong Teeth Dental Cream 300g", 'brand': "Colgate", 'product_type': "Toothpaste", 'variant': "300g Saver Pack", 'pack_size': "300g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 165.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.colgate.com/en-in", 'image_source_url': None, 'notes': "Colgate Strong Teeth 300g saver pack." },
    {'item_no': 78, 'source_name': "COLGATE VEDSHIAIKTI 100G", 'display_name': "Colgate Vedshakti Ayurvedic Toothpaste 100g", 'brand': "Colgate", 'product_type': "Toothpaste", 'variant': "100g Tube", 'pack_size': "100g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 60.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.colgate.com/en-in", 'image_source_url': None, 'notes': "Colgate Vedshakti 100g (spelling corrected from VEDSHIAIKTI)." },
    {'item_no': 79, 'source_name': "COLOUR PAPAD 250G", 'display_name': "Colour Fryums Papad 250g", 'brand': "G1 Mart Selection", 'product_type': "Papad / Fryums", 'variant': "250g Pouch", 'pack_size': "250g", 'unit': "Pieces", 'category': "snacks", 'mrp': 35.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "MEDIUM", 'product_source_url': None, 'image_source_url': None, 'notes': "Colour star / ring fryums papad 250g." },
    {'item_no': 80, 'source_name': "Comfort 30ml", 'display_name': "Comfort After Wash Fabric Conditioner 30ml Sachet", 'brand': "Comfort", 'product_type': "Fabric Conditioner", 'variant': "30ml Sachet", 'pack_size': "30ml", 'unit': "Pieces", 'category': "household", 'mrp': 5.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.hul.co.in", 'image_source_url': None, 'notes': "Comfort Morning Fresh 30ml ₹5 sachet." },
    {'item_no': 81, 'source_name': "Comfort Morning Fresh 210 Ml", 'display_name': "Comfort Morning Fresh Fabric Conditioner 210ml", 'brand': "Comfort", 'product_type': "Fabric Conditioner", 'variant': "Morning Fresh 210ml", 'pack_size': "210ml", 'unit': "Pieces", 'category': "household", 'mrp': 60.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.hul.co.in", 'image_source_url': None, 'notes': "Comfort Morning Fresh 210ml bottle." },
    {'item_no': 82, 'source_name': "COMFORT ROYAL 80ML", 'display_name': "Comfort Royal Fabric Conditioner 80ml", 'brand': "Comfort", 'product_type': "Fabric Conditioner", 'variant': "Royal 80ml", 'pack_size': "80ml", 'unit': "Pieces", 'category': "household", 'mrp': 30.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.hul.co.in", 'image_source_url': None, 'notes': "Comfort Royal fragrance fabric conditioner." },
    {'item_no': 83, 'source_name': "CORIANDER 100G", 'display_name': "Whole Coriander Seeds (Dhaniyalu) 100g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "100g", 'pack_size': "100g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Whole Coriander Seeds 100g." },
    {'item_no': 84, 'source_name': "CORIANDER POWDER 100G", 'display_name': "Pure Coriander Powder (Dhaniyala Podi) 100g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "100g", 'pack_size': "100g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 35.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Dhaniyala Podi 100g." },
    {'item_no': 85, 'source_name': "CORIANDER POWDER 50G", 'display_name': "Pure Coriander Powder (Dhaniyala Podi) 50g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "50g", 'pack_size': "50g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 18.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Dhaniyala Podi 50g." },
    {'item_no': 86, 'source_name': "CORIANDER SEEDS 250G", 'display_name': "Whole Coriander Seeds (Dhaniyalu) 250g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "250g", 'pack_size': "250g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 55.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Whole Coriander Seeds 250g." },
    {'item_no': 87, 'source_name': "CURD", 'display_name': "Fresh Traditional Pouch Curd 500g", 'brand': "G1 Mart Fresh", 'product_type': "Dairy", 'variant': "500g Pouch", 'pack_size': "500g", 'unit': "Pieces", 'category': "dairy-bakery", 'mrp': 35.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Fresh Curd 500g pouch." },
    {'item_no': 88, 'source_name': "DABUR RED 100G", 'display_name': "Dabur Red Ayurvedic Toothpaste 100g", 'brand': "Dabur", 'product_type': "Toothpaste", 'variant': "100g Tube", 'pack_size': "100g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 60.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.dabur.com", 'image_source_url': None, 'notes': "Dabur Red Ayurvedic toothpaste 100g." },
    {'item_no': 89, 'source_name': "DABUR RED 300G", 'display_name': "Dabur Red Ayurvedic Toothpaste 300g (Family Pack)", 'brand': "Dabur", 'product_type': "Toothpaste", 'variant': "300g Pack", 'pack_size': "300g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 155.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.dabur.com", 'image_source_url': None, 'notes': "Dabur Red 300g Family Pack." },
    {'item_no': 90, 'source_name': "DABUR RED 50G", 'display_name': "Dabur Red Ayurvedic Toothpaste 50g", 'brand': "Dabur", 'product_type': "Toothpaste", 'variant': "50g Tube", 'pack_size': "50g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 30.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.dabur.com", 'image_source_url': None, 'notes': "Dabur Red 50g tube." },
    {'item_no': 91, 'source_name': "DAIRY MILK 10RS", 'display_name': "Cadbury Dairy Milk Chocolate Bar 12g (Rs 10)", 'brand': "Cadbury", 'product_type': "Chocolate", 'variant': "12g / Rs 10", 'pack_size': "12g", 'unit': "Pieces", 'category': "snacks", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.cadbury.in", 'image_source_url': None, 'notes': "Cadbury Dairy Milk ₹10 packshot." },
    {'item_no': 92, 'source_name': "DAIRY MILK 5RS", 'display_name': "Cadbury Dairy Milk Chocolate Bar 6.5g (Rs 5)", 'brand': "Cadbury", 'product_type': "Chocolate", 'variant': "6.5g / Rs 5", 'pack_size': "6.5g", 'unit': "Pieces", 'category': "snacks", 'mrp': 5.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.cadbury.in", 'image_source_url': None, 'notes': "Cadbury Dairy Milk ₹5 packshot." },
    {'item_no': 93, 'source_name': "DARK FANTASY", 'display_name': "Sunfeast Dark Fantasy Choco Fills 75g", 'brand': "Dark Fantasy", 'product_type': "Cookies", 'variant': "Choco Fills 75g", 'pack_size': "75g", 'unit': "Pieces", 'category': "snacks", 'mrp': 40.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.itcstore.in", 'image_source_url': None, 'notes': "Sunfeast Dark Fantasy Choco Fills 75g." },
    {'item_no': 94, 'source_name': "DARK FANTASY BOURBON 90G", 'display_name': "Sunfeast Dark Fantasy Bourbon Biscuits 90g", 'brand': "Dark Fantasy", 'product_type': "Cookies", 'variant': "Bourbon 90g", 'pack_size': "90g", 'unit': "Pieces", 'category': "snacks", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.itcstore.in", 'image_source_url': None, 'notes': "Sunfeast Dark Fantasy Bourbon 90g." },
    {'item_no': 95, 'source_name': "Dark Fantasy Choco Fills 10g", 'display_name': "Sunfeast Dark Fantasy Choco Fills Single Cookie (Rs 5)", 'brand': "Dark Fantasy", 'product_type': "Cookies", 'variant': "Choco Fills 10g", 'pack_size': "10g", 'unit': "Pieces", 'category': "snacks", 'mrp': 5.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.itcstore.in", 'image_source_url': None, 'notes': "Dark Fantasy Choco Fills single cookie pack." },
    {'item_no': 96, 'source_name': "DARK FANTASY CHOCOLATE COOKIE", 'display_name': "Sunfeast Dark Fantasy Choco Meltz 50g", 'brand': "Dark Fantasy", 'product_type': "Cookies", 'variant': "Choco Meltz 50g", 'pack_size': "50g", 'unit': "Pieces", 'category': "snacks", 'mrp': 30.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.itcstore.in", 'image_source_url': None, 'notes': "Dark Fantasy Chocolate Cookie." },
    {'item_no': 97, 'source_name': "Dark Fantasy Cookis", 'display_name': "Sunfeast Dark Fantasy Choco Nut Fills 75g", 'brand': "Dark Fantasy", 'product_type': "Cookies", 'variant': "Nut Fills 75g", 'pack_size': "75g", 'unit': "Pieces", 'category': "snacks", 'mrp': 40.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.itcstore.in", 'image_source_url': None, 'notes': "Dark Fantasy Cookies." },
    {'item_no': 98, 'source_name': "DARK FANTASY VANILLA 55G", 'display_name': "Sunfeast Dark Fantasy Vanilla Fills 55g", 'brand': "Dark Fantasy", 'product_type': "Cookies", 'variant': "Vanilla Fills 55g", 'pack_size': "55g", 'unit': "Pieces", 'category': "snacks", 'mrp': 30.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.itcstore.in", 'image_source_url': None, 'notes': "Dark Fantasy Vanilla Fills 55g." },
    {'item_no': 99, 'source_name': "DARK FANTASY5RS", 'display_name': "Sunfeast Dark Fantasy Choco Fills (Rs 5 Pack)", 'brand': "Dark Fantasy", 'product_type': "Cookies", 'variant': "Rs 5 Pack", 'pack_size': "1 pc", 'unit': "Pieces", 'category': "snacks", 'mrp': 5.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.itcstore.in", 'image_source_url': None, 'notes': "Dark Fantasy ₹5 pack." },
    {'item_no': 100, 'source_name': "DESI POPZ", 'display_name': "GO DESi POPZ Tangy Imli Candy", 'brand': "GO DESi", 'product_type': "Lollipop Candy", 'variant': "Imli Pop", 'pack_size': "1 pc", 'unit': "Pieces", 'category': "snacks", 'mrp': 5.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://godesi.in", 'image_source_url': None, 'notes': "GO DESi Real Desi Popz Imli." },
    {'item_no': 101, 'source_name': "DETTAL 250 ML", 'display_name': "Dettol Antiseptic Liquid Disinfectant 250ml", 'brand': "Dettol", 'product_type': "Antiseptic Liquid", 'variant': "250ml Bottle", 'pack_size': "250ml", 'unit': "Pieces", 'category': "personal-care", 'mrp': 155.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.dettol.co.in", 'image_source_url': None, 'notes': "Dettol Antiseptic Liquid 250ml (spelling corrected from DETTAL)." },
    {'item_no': 102, 'source_name': "DOMEX POWDER", 'display_name': "Domex Disinfectant Floor Cleaning Powder", 'brand': "Domex", 'product_type': "Floor Cleaner", 'variant': "Powder", 'pack_size': "500g", 'unit': "Pieces", 'category': "household", 'mrp': 50.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.hul.co.in", 'image_source_url': None, 'notes': "Domex Cleaning Powder." },
    {'item_no': 103, 'source_name': "DOVE HAIR SHAMPOO6ML", 'display_name': "Dove Daily Shine Shampoo 6ml Sachet", 'brand': "Dove", 'product_type': "Shampoo", 'variant': "6ml Sachet / Rs 2", 'pack_size': "6ml", 'unit': "Pieces", 'category': "personal-care", 'mrp': 2.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.dove.com/in", 'image_source_url': None, 'notes': "Dove Daily Shine ₹2 sachet." },
    {'item_no': 104, 'source_name': "DOVE SHAMPOO", 'display_name': "Dove Intense Repair Shampoo 80ml", 'brand': "Dove", 'product_type': "Shampoo", 'variant': "80ml Bottle", 'pack_size': "80ml", 'unit': "Pieces", 'category': "personal-care", 'mrp': 85.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.dove.com/in", 'image_source_url': None, 'notes': "Dove Intense Repair shampoo 80ml." },
    {'item_no': 105, 'source_name': "DOVE SOP BAR", 'display_name': "Dove Cream Beauty Bathing Bar 100g", 'brand': "Dove", 'product_type': "Soap", 'variant': "100g Bar", 'pack_size': "100g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 68.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.dove.com/in", 'image_source_url': None, 'notes': "Dove Cream Beauty Bathing Bar (spelling corrected from DOVE SOP BAR)." },
    {'item_no': 106, 'source_name': "DRY NUTS BOL", 'display_name': "Dry Fruits & Mixed Nuts Bowl Pack 100g", 'brand': "G1 Mart Selection", 'product_type': "Dry Fruits", 'variant': "100g Bowl", 'pack_size': "100g", 'unit': "Pieces", 'category': "snacks", 'mrp': 150.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "MEDIUM", 'product_source_url': None, 'image_source_url': None, 'notes': "Mixed dry fruits bowl pack." },
    {'item_no': 107, 'source_name': "DUSTPAN", 'display_name': "Heavy Duty Plastic Cleaning Dustpan", 'brand': "G1 Mart Selection", 'product_type': "Cleaning Tools", 'variant': "Standard", 'pack_size': "1 unit", 'unit': "Pieces", 'category': "household", 'mrp': 60.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Plastic cleaning dustpan." },
    {'item_no': 108, 'source_name': "E BUTES", 'display_name': "E Butes Shorthand SKU", 'brand': None, 'product_type': "Unknown", 'variant': None, 'pack_size': None, 'unit': "Pieces", 'category': "household", 'mrp': None, 'selling_price': None, 'product_match_status': "NEEDS_REVIEW", 'image_match_status': "NEEDS_REVIEW", 'confidence': "LOW", 'product_source_url': None, 'image_source_url': None, 'notes': "Shorthand sales code 'E BUTES'. Unidentifiable without physical SKU check." },
    {'item_no': 109, 'source_name': "EAGLE SAMBRANI 50G", 'display_name': "Eagle Brand Pure Sambrani Dhoop Cup 50g", 'brand': "Eagle", 'product_type': "Pooja Essentials", 'variant': "50g Box", 'pack_size': "50g", 'unit': "Pieces", 'category': "household", 'mrp': 40.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Eagle Brand Sambrani 50g." },
    {'item_no': 110, 'source_name': "Ear Buts", 'display_name': "Cotton Ear Buds Pack", 'brand': None, 'product_type': "Personal Hygiene", 'variant': "Plastic Stem", 'pack_size': "100 tips", 'unit': "Pieces", 'category': "personal-care", 'mrp': None, 'selling_price': None, 'product_match_status': "NEEDS_REVIEW", 'image_match_status': "NEEDS_REVIEW", 'confidence': "LOW", 'product_source_url': None, 'image_source_url': None, 'notes': "Unbranded generic ear buds pack. Requires store packaging check." },
    {'item_no': 111, 'source_name': "Eggs", 'display_name': "Fresh Farm White Eggs (Pack of 6)", 'brand': "G1 Mart Fresh", 'product_type': "Eggs", 'variant': "Pack of 6", 'pack_size': "6 pcs", 'unit': "Pieces", 'category': "dairy-bakery", 'mrp': 42.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Farm fresh white table eggs." },
    {'item_no': 112, 'source_name': "EGGS TRA", 'display_name': "Fresh Farm White Eggs Tray (Pack of 30)", 'brand': "G1 Mart Fresh", 'product_type': "Eggs", 'variant': "Tray of 30", 'pack_size': "30 pcs", 'unit': "Pieces", 'category': "dairy-bakery", 'mrp': 210.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Full egg tray of 30 eggs." },
    {'item_no': 113, 'source_name': "ELACHI", 'display_name': "Whole Green Cardamom (Yalukalu) 20g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "20g", 'pack_size': "20g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 60.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Green Cardamom 20g." },
    {'item_no': 114, 'source_name': "ELAICHI 10G", 'display_name': "Whole Green Cardamom (Yalukalu) 10g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "10g", 'pack_size': "10g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 30.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Green Cardamom 10g." },
    {'item_no': 115, 'source_name': "ELAICHI RUSK 182G", 'display_name': "Britannia Toastea Premium Elaichi Rusk 182g", 'brand': "Britannia", 'product_type': "Bakery / Rusk", 'variant': "Elaichi 182g", 'pack_size': "182g", 'unit': "Pieces", 'category': "snacks", 'mrp': 35.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://britannia.co.in", 'image_source_url': None, 'notes': "Britannia Toastea Elaichi Rusk 182g." },
    {'item_no': 116, 'source_name': "ELAICHI RUSK 58G", 'display_name': "Britannia Toastea Elaichi Rusk 58g", 'brand': "Britannia", 'product_type': "Bakery / Rusk", 'variant': "Elaichi 58g", 'pack_size': "58g", 'unit': "Pieces", 'category': "snacks", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://britannia.co.in", 'image_source_url': None, 'notes': "Britannia Toastea Elaichi Rusk ₹10 pack." },
    {'item_no': 117, 'source_name': "ENDU MERCHI 250G", 'display_name': "Guntur Dry Red Chillies (Endu Mirchi) 250g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "250g Pouch", 'pack_size': "250g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 85.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Dried Guntur Chillies 250g." },
    {'item_no': 118, 'source_name': "ENDU MERCHI 500G", 'display_name': "Guntur Dry Red Chillies (Endu Mirchi) 500g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "500g Pouch", 'pack_size': "500g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 165.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Dried Guntur Chillies 500g." },
    {'item_no': 119, 'source_name': "ENO", 'display_name': "Eno Fruit Salt Regular / Lemon 5g Sachet", 'brand': "Eno", 'product_type': "Digestive Health", 'variant': "5g Sachet", 'pack_size': "5g", 'unit': "Pieces", 'category': "household", 'mrp': 9.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.eno.co.in", 'image_source_url': None, 'notes': "GSK Eno Fruit Salt sachet." },
    {'item_no': 120, 'source_name': "EXO", 'display_name': "Exo Touch & Shine Anti-Bacterial Dishwash Bar 150g", 'brand': "Exo", 'product_type': "Dishwash", 'variant': "150g Bar", 'pack_size': "150g", 'unit': "Pieces", 'category': "household", 'mrp': 20.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://jyothylabs.com", 'image_source_url': None, 'notes': "Exo Dishwash Bar 150g." },
    {'item_no': 121, 'source_name': "Exo 10", 'display_name': "Exo Touch & Shine Dishwash Bar (Rs 10 Pack)", 'brand': "Exo", 'product_type': "Dishwash", 'variant': "Rs 10 Pack", 'pack_size': "80g", 'unit': "Pieces", 'category': "household", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://jyothylabs.com", 'image_source_url': None, 'notes': "Exo ₹10 Dishwash bar." },
    {'item_no': 122, 'source_name': "Exo 5", 'display_name': "Exo Dishwash Bar (Rs 5 Pack)", 'brand': "Exo", 'product_type': "Dishwash", 'variant': "Rs 5 Pack", 'pack_size': "40g", 'unit': "Pieces", 'category': "household", 'mrp': 5.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://jyothylabs.com", 'image_source_url': None, 'notes': "Exo ₹5 Dishwash bar." },
    {'item_no': 123, 'source_name': "EXO POWDER 5600G", 'display_name': "Exo Super Dishwash Powder 500g", 'brand': "Exo", 'product_type': "Dishwash", 'variant': "500g Tub / Pack", 'pack_size': "500g", 'unit': "Pieces", 'category': "household", 'mrp': 40.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://jyothylabs.com", 'image_source_url': None, 'notes': "Exo Dishwash Powder." },
    {'item_no': 124, 'source_name': "EXO SCRUBRS", 'display_name': "Exo Stainless Steel Dishwash Scrubber", 'brand': "Exo", 'product_type': "Dishwash", 'variant': "Steel Scrubber", 'pack_size': "1 pc", 'unit': "Pieces", 'category': "household", 'mrp': 15.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://jyothylabs.com", 'image_source_url': None, 'notes': "Exo Stainless Steel Scrubber." },
    {'item_no': 125, 'source_name': "FAB LIQ 825G", 'display_name': "Henko Matic / Fab Liquid Detergent 825ml", 'brand': "Henko", 'product_type': "Liquid Detergent", 'variant': "825ml Bottle", 'pack_size': "825ml", 'unit': "Pieces", 'category': "household", 'mrp': 165.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Fab / Henko Liquid Detergent 825ml." },
    {'item_no': 126, 'source_name': "FAB LIQUID 10", 'display_name': "Fab Liquid Detergent Sachet (Rs 10)", 'brand': "Henko", 'product_type': "Liquid Detergent", 'variant': "Rs 10 Sachet", 'pack_size': "Sachet", 'unit': "Pieces", 'category': "household", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Fab Liquid Detergent ₹10 sachet." },
    {'item_no': 127, 'source_name': "FAIR LOVELI RE NEW 2.78G", 'display_name': "Glow & Lovely Advanced Multivitamin Cream 9g", 'brand': "Glow & Lovely", 'product_type': "Skincare", 'variant': "9g Tube", 'pack_size': "9g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.hul.co.in", 'image_source_url': None, 'notes': "Glow & Lovely Multivitamin (formerly Fair & Lovely)." },
    {'item_no': 128, 'source_name': "FANTA 10RUPEES", 'display_name': "Fanta Orange Flavoured Carbonated Drink (Rs 10 Returnable / Mini Can)", 'brand': "Fanta", 'product_type': "Cold Drinks", 'variant': "Rs 10 Pack", 'pack_size': "200ml", 'unit': "Pieces", 'category': "beverages", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.coca-cola.com/in/en", 'image_source_url': None, 'notes': "Fanta Orange ₹10 pack." },
    {'item_no': 129, 'source_name': "FINGER MILLET 500G", 'display_name': "Whole Finger Millet / Ragi Seeds 500g", 'brand': "G1 Mart Selection", 'product_type': "Millets", 'variant': "500g", 'pack_size': "500g", 'unit': "Packs", 'category': "rice-dal-atta", 'mrp': 45.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Ragi / Finger Millet 500g." },
    {'item_no': 130, 'source_name': "FLAIR CARBONIX0.7MM", 'display_name': "Flair Carbonix 0.7mm Ball Pen", 'brand': "Flair", 'product_type': "Stationery", 'variant': "0.7mm Ball Pen", 'pack_size': "1 pc", 'unit': "Pieces", 'category': "household", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.flairworld.com", 'image_source_url': None, 'notes': "Flair Carbonix 0.7mm ball pen." },
    {'item_no': 131, 'source_name': "FLATTENED RICE 250G", 'display_name': "Flattened Rice / Medium Poha (Atukulu) 250g", 'brand': "G1 Mart Selection", 'product_type': "Poha / Atukulu", 'variant': "250g Pouch", 'pack_size': "250g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Medium Poha 250g." },
    {'item_no': 132, 'source_name': "FLATTENED RICE 500G", 'display_name': "Flattened Rice / Medium Poha (Atukulu) 500g", 'brand': "G1 Mart Selection", 'product_type': "Poha / Atukulu", 'variant': "500g Pouch", 'pack_size': "500g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 48.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Medium Poha 500g." },
    {'item_no': 133, 'source_name': "FOGG SPRAY", 'display_name': "Fogg Fresh Oriental / Master Body Spray 120ml", 'brand': "Fogg", 'product_type': "Deodorant", 'variant': "120ml", 'pack_size': "120ml", 'unit': "Pieces", 'category': "personal-care", 'mrp': 225.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Fogg No Gas Deodorant Spray." },
    {'item_no': 134, 'source_name': "Freedam Oil 500ml", 'display_name': "Freedom Refined Sunflower Oil 500ml", 'brand': "Freedom", 'product_type': "Cooking Oil", 'variant': "500ml Pouch", 'pack_size': "500ml", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 75.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.freedomcart.com", 'image_source_url': None, 'notes': "Freedom Refined Sunflower Oil 500ml." },
    {'item_no': 135, 'source_name': "Freedom 1LT", 'display_name': "Freedom Refined Sunflower Oil 1L Pouch", 'brand': "Freedom", 'product_type': "Cooking Oil", 'variant': "1L Pouch", 'pack_size': "1 L", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 145.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.freedomcart.com", 'image_source_url': None, 'notes': "Freedom Sunflower Oil 1L." },
    {'item_no': 136, 'source_name': "FREEDOM GROUNDNUT OLI 1L", 'display_name': "Freedom Filtered Groundnut Oil 1L Pouch", 'brand': "Freedom", 'product_type': "Cooking Oil", 'variant': "Groundnut Oil 1L", 'pack_size': "1 L", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 195.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.freedomcart.com", 'image_source_url': None, 'notes': "Freedom Filtered Groundnut Oil 1L." },
    {'item_no': 137, 'source_name': "FREEDOM OIL 1L", 'display_name': "Freedom Refined Sunflower Oil 1L Pouch", 'brand': "Freedom", 'product_type': "Cooking Oil", 'variant': "1L Pouch", 'pack_size': "1 L", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 145.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.freedomcart.com", 'image_source_url': None, 'notes': "Freedom Sunflower Oil 1L pouch." },
    {'item_no': 138, 'source_name': "FREEDOM RICE 1L", 'display_name': "Freedom Physically Refined Rice Bran Oil 1L", 'brand': "Freedom", 'product_type': "Cooking Oil", 'variant': "Rice Bran 1L", 'pack_size': "1 L", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 155.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.freedomcart.com", 'image_source_url': None, 'notes': "Freedom Rice Bran Oil 1L." },
    {'item_no': 139, 'source_name': "Fried Rice Masala 20g", 'display_name': "Ching's Secret Fried Rice Masala 20g", 'brand': "Ching's Secret", 'product_type': "Masala", 'variant': "20g Sachet", 'pack_size': "20g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://chingssecret.com", 'image_source_url': None, 'notes': "Ching's Secret Secret Fried Rice Masala ₹10." },
    {'item_no': 140, 'source_name': "Gadda Camphpr 25g", 'display_name': "Pure Pooja Camphor Lump (Gadda Karpooram) 25g", 'brand': "G1 Mart Selection", 'product_type': "Pooja Essentials", 'variant': "25g Pack", 'pack_size': "25g", 'unit': "Pieces", 'category': "household", 'mrp': 30.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Pooja Gadda Camphor 25g." },
    {'item_no': 141, 'source_name': "GANGI PENDI 100G", 'display_name': "Laundry Starch Powder (Gangi Pindi) 100g", 'brand': "G1 Mart Selection", 'product_type': "Laundry Care", 'variant': "100g", 'pack_size': "100g", 'unit': "Pieces", 'category': "household", 'mrp': 20.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gangi Pindi Starch Powder 100g." },
    {'item_no': 142, 'source_name': "GARLIC MIXTURE 100G", 'display_name': "Spicy Garlic Namkeen Mixture (Vellulli Mixture) 100g", 'brand': "G1 Mart Selection", 'product_type': "Snacks / Namkeen", 'variant': "100g Pouch", 'pack_size': "100g", 'unit': "Pieces", 'category': "snacks", 'mrp': 30.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Spicy Garlic Mixture 100g." },
    {'item_no': 143, 'source_name': "GARNIER F . W", 'display_name': "Garnier Skin Naturals Bright Complete Face Wash 50g", 'brand': "Garnier", 'product_type': "Face Wash", 'variant': "50g Tube", 'pack_size': "50g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 99.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.garnier.in", 'image_source_url': None, 'notes': "Garnier Bright Complete Face Wash 50g." },
    {'item_no': 144, 'source_name': "GAYATHARI SAMBRANI STICK", 'display_name': "Gayathri Dhoop Sambrani Sticks (Pack of 10)", 'brand': "Gayathri", 'product_type': "Pooja Essentials", 'variant': "10 sticks", 'pack_size': "10 pcs", 'unit': "Pieces", 'category': "household", 'mrp': 20.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gayathri Dhoop Sambrani Sticks." },
    {'item_no': 145, 'source_name': "Gelakara 50g", 'display_name': "Whole Cumin Seeds (Jeelakarra) 50g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "50g Pouch", 'pack_size': "50g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 35.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Whole Cumin Seeds 50g." },
    {'item_no': 146, 'source_name': "GEMINI TEE 100G", 'display_name': "Tata Gemini Strong Dust Tea 100g", 'brand': "Gemini", 'product_type': "Tea", 'variant': "100g Pouch", 'pack_size': "100g", 'unit': "Pieces", 'category': "beverages", 'mrp': 40.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.tataconsumer.com", 'image_source_url': None, 'notes': "Tata Gemini Tea 100g (spelling corrected from GEMINI TEE)." },
    {'item_no': 147, 'source_name': "Gilakara 100g", 'display_name': "Whole Cumin Seeds (Jeelakarra) 100g", 'brand': "G1 Mart Selection", 'product_type': "Spices", 'variant': "100g Pouch", 'pack_size': "100g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 65.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Whole Cumin Seeds 100g." },
    {'item_no': 148, 'source_name': "Gkl Black Dates", 'display_name': "Gokulam Premium Black Dates 500g", 'brand': "Gokulam", 'product_type': "Dry Fruits", 'variant': "500g Box", 'pack_size': "500g", 'unit': "Pieces", 'category': "snacks", 'mrp': 160.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gokulam Black Dates 500g." },
    {'item_no': 149, 'source_name': "GKL SEEDED 250G", 'display_name': "GKL Seeded Dates 250g", 'brand': None, 'product_type': "Dates", 'variant': "250g", 'pack_size': "250g", 'unit': "Pieces", 'category': "snacks", 'mrp': None, 'selling_price': None, 'product_match_status': "NEEDS_REVIEW", 'image_match_status': "NEEDS_REVIEW", 'confidence': "LOW", 'product_source_url': None, 'image_source_url': None, 'notes': "Shorthand sales code 'GKL SEEDED 250G'. Ambiguous regional entry." },
    {'item_no': 150, 'source_name': "GLOW & LOVELY", 'display_name': "Glow & Lovely Advanced Multivitamin Cream 25g", 'brand': "Glow & Lovely", 'product_type': "Skincare", 'variant': "25g Tube", 'pack_size': "25g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 65.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.hul.co.in", 'image_source_url': None, 'notes': "Glow & Lovely Multivitamin 25g." },
    {'item_no': 151, 'source_name': "Glow&lovely 20g", 'display_name': "Glow & Lovely Advanced Multivitamin Cream 20g", 'brand': "Glow & Lovely", 'product_type': "Skincare", 'variant': "20g Tube", 'pack_size': "20g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 55.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.hul.co.in", 'image_source_url': None, 'notes': "Glow & Lovely Multivitamin 20g." },
    {'item_no': 152, 'source_name': "GN GOLD LIQ", 'display_name': "Goodnight Gold Flash Mosquito Liquid Refill 45ml", 'brand': "Goodknight", 'product_type': "Mosquito Repellent", 'variant': "45ml Refill", 'pack_size': "45ml", 'unit': "Pieces", 'category': "household", 'mrp': 85.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.goodknight.in", 'image_source_url': None, 'notes': "Goodknight Gold Flash liquid refill 45ml." },
    {'item_no': 153, 'source_name': "GN GOLD MATCH", 'display_name': "Goodnight Gold Flash Machine & Refill Combo", 'brand': "Goodknight", 'product_type': "Mosquito Repellent", 'variant': "Machine + 45ml", 'pack_size': "Combo", 'unit': "Pieces", 'category': "household", 'mrp': 110.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.goodknight.in", 'image_source_url': None, 'notes': "Goodknight Gold Flash combi pack." },
    {'item_no': 154, 'source_name': "GOKILAM DATES 250G", 'display_name': "Gokulam Premium Wet Dates 250g", 'brand': "Gokulam", 'product_type': "Dry Fruits", 'variant': "250g Pack", 'pack_size': "250g", 'unit': "Pieces", 'category': "snacks", 'mrp': 75.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gokulam Wet Dates 250g." },
    {'item_no': 155, 'source_name': "GOKUL SANTOL POWDER 30G", 'display_name': "Gokul Santol Pure Sandal Talc 30g", 'brand': "Gokul", 'product_type': "Talcum Powder", 'variant': "30g", 'pack_size': "30g", 'unit': "Pieces", 'category': "personal-care", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gokul Santol Sandal Talcum Powder 30g." },
    {'item_no': 156, 'source_name': "Gokulam Dates", 'display_name': "Gokulam Premium Seedless Dates 500g", 'brand': "Gokulam", 'product_type': "Dry Fruits", 'variant': "500g", 'pack_size': "500g", 'unit': "Pieces", 'category': "snacks", 'mrp': 150.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gokulam Seedless Dates 500g." },
    {'item_no': 157, 'source_name': "GONGURA PICKELS 60G", 'display_name': "Priya Gongura Pickle with Garlic 60g Sachet", 'brand': "Priya", 'product_type': "Pickles", 'variant': "60g Sachet / Rs 10", 'pack_size': "60g", 'unit': "Pieces", 'category': "rice-dal-atta", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.priyafoods.com", 'image_source_url': None, 'notes': "Priya Gongura Pickle ₹10 sachet." },
    {'item_no': 158, 'source_name': "Gopuram", 'display_name': "Gopuram Pure Pooja Turmeric Powder (Pasupu) 50g", 'brand': "Gopuram", 'product_type': "Pooja Essentials", 'variant': "50g Pouch", 'pack_size': "50g", 'unit': "Pieces", 'category': "household", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gopuram Pasupu 50g." },
    {'item_no': 159, 'source_name': "GOPURAM 20G", 'display_name': "Gopuram Pure Pooja Turmeric Powder (Pasupu) 20g", 'brand': "Gopuram", 'product_type': "Pooja Essentials", 'variant': "20g Pouch", 'pack_size': "20g", 'unit': "Pieces", 'category': "household", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gopuram Pasupu 20g ₹10 pouch." },
    {'item_no': 160, 'source_name': "Gopuram Turmeric Powder 20g", 'display_name': "Gopuram Pure Turmeric Powder 20g", 'brand': "Gopuram", 'product_type': "Pooja Essentials", 'variant': "20g", 'pack_size': "20g", 'unit': "Pieces", 'category': "household", 'mrp': 10.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gopuram Pasupu 20g." },
    {'item_no': 161, 'source_name': "Gopuram Turmeric Powder 50", 'display_name': "Gopuram Pure Turmeric Powder 50g", 'brand': "Gopuram", 'product_type': "Pooja Essentials", 'variant': "50g", 'pack_size': "50g", 'unit': "Pieces", 'category': "household", 'mrp': 25.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': None, 'image_source_url': None, 'notes': "Gopuram Pasupu 50g." },
    {'item_no': 162, 'source_name': "GRB GHEE", 'display_name': "GRB Pure Cow Ghee 200ml Pouch", 'brand': "GRB", 'product_type': "Ghee", 'variant': "200ml Pouch", 'pack_size': "200ml", 'unit': "Pieces", 'category': "dairy-bakery", 'mrp': 165.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.grbdairy.com", 'image_source_url': None, 'notes': "GRB Pure Ghee 200ml pouch." },
    {'item_no': 163, 'source_name': "GRB GHEE50ML", 'display_name': "GRB Pure Cow Ghee 50ml Sachet", 'brand': "GRB", 'product_type': "Ghee", 'variant': "50ml", 'pack_size': "50ml", 'unit': "Pieces", 'category': "dairy-bakery", 'mrp': 45.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.grbdairy.com", 'image_source_url': None, 'notes': "GRB Pure Ghee 50ml sachet." },
    {'item_no': 164, 'source_name': "GULAB JAM (1+1) 160GM", 'display_name': "MTR Gulab Jamun Instant Mix (1+1 Offer) 160g+160g", 'brand': "MTR", 'product_type': "Ready Mix", 'variant': "160g (1+1 Combo)", 'pack_size': "320g", 'unit': "Pieces", 'category': "snacks", 'mrp': 120.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.mtrfoods.com", 'image_source_url': None, 'notes': "MTR Gulab Jamun Mix 1+1 offer." },
    {'item_no': 165, 'source_name': "GULAB JAMUM MIX", 'display_name': "Gits Gulab Jamun Instant Mix 200g", 'brand': "Gits", 'product_type': "Ready Mix", 'variant': "200g Box", 'pack_size': "200g", 'unit': "Pieces", 'category': "snacks", 'mrp': 85.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.gitsfood.com", 'image_source_url': None, 'notes': "Gits Gulab Jamun instant dessert mix." },
    {'item_no': 166, 'source_name': "GUM 5RS", 'display_name': "Fevicol MR / Kores Synthetic Gum (Rs 5 Tube)", 'brand': "Pidilite", 'product_type': "Stationery", 'variant': "Rs 5 Pack", 'pack_size': "1 pc", 'unit': "Pieces", 'category': "household", 'mrp': 5.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.pidilite.com", 'image_source_url': None, 'notes': "Pidilite Synthetic Adhesive Gum ₹5 tube." },
    {'item_no': 167, 'source_name': "Harpic Blue 600m", 'display_name': "Harpic Disinfectant Bathroom & Toilet Cleaner Blue 600ml", 'brand': "Harpic", 'product_type': "Toilet Cleaner", 'variant': "Power Plus 600ml", 'pack_size': "600ml", 'unit': "Pieces", 'category': "household", 'mrp': 115.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.harpic.co.in", 'image_source_url': None, 'notes': "Harpic Power Plus Blue 600ml." },
    {'item_no': 168, 'source_name': "Harpic Red 500ml", 'display_name': "Harpic Bathroom Cleaner Power Plus Red 500ml", 'brand': "Harpic", 'product_type': "Bathroom Cleaner", 'variant': "Red 500ml", 'pack_size': "500ml", 'unit': "Pieces", 'category': "household", 'mrp': 105.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.harpic.co.in", 'image_source_url': None, 'notes': "Harpic Bathroom Cleaner Red 500ml." },
    {'item_no': 169, 'source_name': "HATSUN CURD", 'display_name': "Hatsun Daily Fresh Curd 500g Pouch", 'brand': "Hatsun", 'product_type': "Dairy", 'variant': "500g Pouch", 'pack_size': "500g", 'unit': "Pieces", 'category': "dairy-bakery", 'mrp': 35.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.hatsun.com", 'image_source_url': None, 'notes': "Hatsun Daily Curd 500g." },
    {'item_no': 170, 'source_name': "HEAD AND SHOULDER 2RS", 'display_name': "Head & Shoulders Anti-Dandruff Cool Menthol Shampoo (Rs 2 Sachet)", 'brand': "Head & Shoulders", 'product_type': "Shampoo", 'variant': "Rs 2 Sachet", 'pack_size': "5.5ml", 'unit': "Pieces", 'category': "personal-care", 'mrp': 2.0, 'selling_price': None, 'product_match_status': "VERIFIED", 'image_match_status': "NEEDS_REVIEW", 'confidence': "HIGH", 'product_source_url': "https://www.pgshop.in", 'image_source_url': None, 'notes': "Head & Shoulders Cool Menthol ₹2 sachet." }
]

def run_batch_3():
    print("=" * 60)
    print("PROCESSING BATCH 3 (Products 71 to 170)")
    print("=" * 60)

    cat_json_path = os.path.join(os.getcwd(), 'src', 'data', 'products-catalog.json')
    with open(cat_json_path, 'r', encoding='utf-8') as f:
        catalog = json.load(f)

    manifest_json_path = os.path.join(os.getcwd(), 'data', 'product-research-manifest.json')
    manifest_csv_path = os.path.join(os.getcwd(), 'data', 'product-research-manifest.csv')

    manifest_records = []
    if os.path.exists(manifest_json_path):
        try:
            with open(manifest_json_path, 'r', encoding='utf-8') as f:
                manifest_records = json.load(f)
        except:
            manifest_records = []

    manifest_dict = {m['item_no']: m for m in manifest_records}

    metrics = {
        'processed': 0,
        'verified': 0,
        'needs_review': 0,
        'unmatched': 0,
        'uploaded': 0,
        'failed': 0,
        'db_updated': 0
    }

    for item in BATCH_3_DATA:
        metrics['processed'] += 1
        item_no = item['item_no']
        p_id = f"g1-prod-{item_no:03d}"
        
        status = item['image_match_status']
        supabase_public_url = None

        if status == 'VERIFIED' and item.get('image_source_url'):
            try:
                req = urllib.request.Request(item['image_source_url'], headers=DOWNLOAD_HEADERS)
                with urllib.request.urlopen(req, timeout=15) as res:
                    raw_bytes = res.read()
                
                clean_bytes, w, h = clean_and_square_image(raw_bytes, target_dim=1200, min_res=400)
                public_url = upload_image_to_supabase(p_id, clean_bytes)
                
                if probe_public_url(public_url):
                    supabase_public_url = public_url
                    metrics['uploaded'] += 1
                    metrics['verified'] += 1
                    print(f"[{item_no:03d}] [OK] Uploaded & Verified: {p_id} -> {public_url}")
                else:
                    status = 'NEEDS_REVIEW'
                    metrics['needs_review'] += 1
                    print(f"[{item_no:03d}] [WARN] Probe failed for {public_url}, marking NEEDS_REVIEW")
            except Exception as e:
                status = 'NEEDS_REVIEW'
                metrics['needs_review'] += 1
                print(f"[{item_no:03d}] [NOTICE] Asset notice for {p_id}: {e}, marking NEEDS_REVIEW")
        else:
            status = 'NEEDS_REVIEW'
            metrics['needs_review'] += 1
            print(f"[{item_no:03d}] [PURGE_SYNTHETIC] {p_id} ({item['source_name']}) cleared to NEEDS_REVIEW (Image NULL)")

        # Record in manifest
        manifest_dict[item_no] = {
            'item_no': item_no,
            'source_name': item['source_name'],
            'display_name': item['display_name'],
            'brand': item['brand'],
            'product_type': item['product_type'],
            'variant': item['variant'],
            'pack_size': item['pack_size'],
            'unit': item['unit'],
            'category': item['category'],
            'mrp': item['mrp'],
            'selling_price': item['selling_price'],
            'product_match_status': item['product_match_status'],
            'image_match_status': status,
            'confidence': item['confidence'],
            'product_source_url': item['product_source_url'],
            'image_source_url': item['image_source_url'],
            'supabase_image_url': supabase_public_url,
            'notes': item['notes']
        }

        # Update Supabase Database
        db_payload = {
            'name': item['display_name'],
            'brand': item['brand'],
            'variant': item['variant'],
            'unit': item['unit'],
            'category_id': item['category'],
            'original_price': item['mrp'],
            'price': item['selling_price'],
            'image_url': supabase_public_url,
            'image_status': status,
            'is_active': True,
            'active': True
        }

        try:
            if update_supabase_product(p_id, db_payload):
                metrics['db_updated'] += 1
            else:
                print(f"[{item_no:03d}] [WARN] DB update status not 200/204 for {p_id}")
        except Exception as e:
            print(f"[{item_no:03d}] [FAIL] DB update error: {e}")

        # Update local catalog array
        for p in catalog:
            if p.get('sourceItemNo') == item_no or p.get('id') == p_id:
                p['name'] = item['display_name']
                p['brand'] = item['brand']
                p['variant'] = item['variant']
                p['unit'] = item['unit']
                p['category'] = item['category']
                p['originalPrice'] = item['mrp']
                p['price'] = item['selling_price']
                p['imageUrl'] = supabase_public_url
                p['image'] = supabase_public_url or '/products/placeholder.svg'
                p['imageStatus'] = status
                break

    # Save manifest JSON & CSV
    manifest_list = sorted(list(manifest_dict.values()), key=lambda x: x['item_no'])
    with open(manifest_json_path, 'w', encoding='utf-8') as f:
        json.dump(manifest_list, f, indent=2)

    with open(manifest_csv_path, 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=[
            'item_no', 'source_name', 'display_name', 'brand', 'product_type',
            'variant', 'pack_size', 'unit', 'category', 'mrp', 'selling_price',
            'product_match_status', 'image_match_status', 'confidence',
            'product_source_url', 'image_source_url', 'supabase_image_url', 'notes'
        ])
        writer.writeheader()
        writer.writerows(manifest_list)

    # Save local catalog
    with open(cat_json_path, 'w', encoding='utf-8') as f:
        json.dump(catalog, f, indent=2)

    print("\n" + "=" * 60)
    print("BATCH 3 SUMMARY METRICS (Items 71 to 170)")
    print("=" * 60)
    print(f"Number Processed:       {metrics['processed']}")
    print(f"Number Verified:        {metrics['verified']}")
    print(f"Number Needs Review:    {metrics['needs_review']}")
    print(f"Number Unmatched:       {metrics['unmatched']}")
    print(f"Number Uploaded:        {metrics['uploaded']}")
    print(f"Number Failed:          {metrics['failed']}")
    print(f"Database Update Count:  {metrics['db_updated']}")
    print("=" * 60)

if __name__ == '__main__':
    run_batch_3()
