const fs = require('fs');
const path = require('path');

// Raw OCR items from G1 MART Item Sales Detail report (Items 1 to 50 for the pilot)
const pilotRaw = [
  { id: 1, name: "5 MUCH", qty: 6.00, unit: "Pieces", total: 30.00 },
  { id: 2, name: "5 STAR 5RS", qty: 5.00, unit: "Pieces", total: 25.00 },
  { id: 3, name: "5 Star Tea 250g", qty: 5.00, unit: "Pieces", total: 375.00 },
  { id: 4, name: "50-50 SWEET&SALTY", qty: 1.00, unit: "Pieces", total: 10.00 },
  { id: 5, name: "707 SOAP", qty: 2.00, unit: "Pieces", total: 20.00 },
  { id: 6, name: "AACHHI GARAM MASALA", qty: 2.00, unit: "Pieces", total: 10.00 },
  { id: 7, name: "AACHI APPALAM 100G", qty: 2.00, unit: "Pieces", total: 84.00 },
  { id: 8, name: "AACHI CHICKEN MASALA", qty: 3.00, unit: "Pieces", total: 15.00 },
  { id: 9, name: "Aashirvaad 1kg", qty: 11.00, unit: "Pieces", total: 715.00 },
  { id: 10, name: "AASHIRVAAD CRYSTAL SALT 1KG", qty: 5.00, unit: "Packs", total: 100.00 },
  { id: 11, name: "AASHIRVAAD SALT", qty: 4.00, unit: "Pieces", total: 112.00 },
  { id: 12, name: "Aashirvaad Suji Rava", qty: 7.00, unit: "Pieces", total: 255.00 },
  { id: 13, name: "Aashirvaad Vermicelli", qty: 1.00, unit: "Pieces", total: 45.00 },
  { id: 14, name: "AASHIRVAAD VERMICELLI 850G", qty: 1.00, unit: "Packs", total: 78.00 },
  { id: 15, name: "ACID 700ML", qty: 1.00, unit: "Pieces", total: 65.00 },
  { id: 16, name: "Ajay Brush", qty: 4.00, unit: "Pieces", total: 80.00 },
  { id: 17, name: "ALL IN ONE 100G", qty: 2.00, unit: "Pieces", total: 110.00 },
  { id: 18, name: "ALLOUT MATCHS", qty: 1.00, unit: "Pieces", total: 100.00 },
  { id: 19, name: "APSARA PENCILS", qty: 2.00, unit: "Pieces", total: 110.00 },
  { id: 20, name: "ARIEL FRONT LIQ 10", qty: 16.00, unit: "Pieces", total: 160.00 },
  { id: 21, name: "Ariel Power Gel Top Load&semi Auto 1kg", qty: 1.00, unit: "Pieces", total: 175.00 },
  { id: 22, name: "AROKYA MILK", qty: 2.00, unit: "Pieces", total: 80.00 },
  { id: 23, name: "ARUN BITES", qty: 21.00, unit: "Pieces", total: 110.00 },
  { id: 24, name: "ARUN DONUT", qty: 20.00, unit: "Pieces", total: 200.00 },
  { id: 25, name: "ARUN DOUBLE", qty: 1.00, unit: "Pieces", total: 60.00 },
  { id: 26, name: "ARUN IBAR", qty: 1.00, unit: "Pieces", total: 90.00 },
  { id: 27, name: "ARUN MILKY FANTASY", qty: 2.00, unit: "Pieces", total: 20.00 },
  { id: 28, name: "Arun Popitos", qty: 6.00, unit: "Pieces", total: 30.00 },
  { id: 29, name: "Arun Sunny Sil", qty: 3.00, unit: "Pieces", total: 30.00 },
  { id: 30, name: "ARUN TOFFEE CON", qty: 6.00, unit: "Pieces", total: 120.00 },
  { id: 31, name: "ASSORATED FRUIT", qty: 2.00, unit: "Pieces", total: 10.00 },
  { id: 32, name: "Avalu 250g", qty: 3.00, unit: "Packs", total: 120.00 },
  { id: 33, name: "Avalu50g", qty: 2.00, unit: "Packs", total: 20.00 },
  { id: 34, name: "BADAM 100GR", qty: 2.00, unit: "Packs", total: 230.00 },
  { id: 35, name: "BADAM 250G", qty: 2.00, unit: "Pieces", total: 560.00 },
  { id: 36, name: "BADAM 50G", qty: 1.00, unit: "Pieces", total: 65.00 },
  { id: 37, name: "BAMBINO MYSORE PACK 200G", qty: 2.00, unit: "Pieces", total: 220.00 },
  { id: 38, name: "BAMBINON VERMICELLI 250G", qty: 3.00, unit: "Pieces", total: 81.00 },
  { id: 39, name: "BANSI RAVA 500G", qty: 3.00, unit: "Pieces", total: 111.00 },
  { id: 40, name: "BAT PAPAD 250G", qty: 1.00, unit: "Pieces", total: 20.00 },
  { id: 41, name: "BINGO CHILLI", qty: 12.00, unit: "Pieces", total: 120.00 },
  { id: 42, name: "BINGO KOREAN", qty: 1.00, unit: "Pieces", total: 50.00 },
  { id: 43, name: "BINGO MASALA", qty: 5.00, unit: "Pieces", total: 100.00 },
  { id: 44, name: "BINGO MASTI", qty: 5.00, unit: "Pieces", total: 100.00 },
  { id: 45, name: "BINGO TOMATO", qty: 1.00, unit: "Pieces", total: 50.00 },
  { id: 46, name: "BINO TEMATO 21G", qty: 7.00, unit: "Pieces", total: 70.00 },
  { id: 47, name: "Biriyani Masala", qty: 2.00, unit: "Pieces", total: 20.00 },
  { id: 48, name: "BISCOTT", qty: 1.00, unit: "Pieces", total: 30.00 },
  { id: 49, name: "BLEACHUNG POWDER 100G", qty: 1.00, unit: "Pieces", total: 12.00 },
  { id: 50, name: "BOOST", qty: 31.00, unit: "Packs", total: 155.00 },
];

// Definition of pilot analysis according to Section 9.1 & 9.2
const pilotCatalog = [
  {
    id: "g1-1",
    itemNumber: 1,
    rawName: "5 MUCH",
    cleanName: "5 Much",
    brand: "Unverified Brand",
    category: "snacks",
    subCategory: "Chocolates & Sweets",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 18,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Ambiguous name in POS. Brand and product variant not stated. Placeholder assigned.",
    description: "Item from G1 Mart inventory awaiting product details verification.",
    rating: 4.8,
    reviewsCount: 15,
    isPopular: true,
    is_ambiguous: true,
    ambiguity_note: "Brand and specific candy/wafer variant unspecified in POS report."
  },
  {
    id: "g1-2",
    itemNumber: 2,
    rawName: "5 STAR 5RS",
    cleanName: "Cadbury 5 Star Chocolate Bar (₹5 Pack)",
    brand: "Cadbury",
    category: "snacks",
    subCategory: "Chocolates & Sweets",
    unit: "1 piece",
    price: 5,
    priceConfirmed: true,
    originalPrice: 5,
    discountPercentage: 0,
    inStock: true,
    stockCount: 15,
    image: "/products/placeholder.svg",
    image_path: "/products/prod-42.jpg",
    image_source: "manufacturer",
    image_license: "Proprietary Brand Pack",
    image_status: "pending",
    image_match_note: "Candidate pack image matches Cadbury 5 Star ₹5 bar. Awaiting user approval in contact sheet.",
    description: "Classic smooth caramel and nougat chocolate bar.",
    rating: 4.8,
    reviewsCount: 16,
    isPopular: true,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-3",
    itemNumber: 3,
    rawName: "5 Star Tea 250g",
    cleanName: "5 Star Tea (250 g)",
    brand: "5 Star Tea",
    category: "beverages",
    subCategory: "Tea & Chai",
    unit: "250 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 15,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Regional brand pack. No approved photo in /product-photos-raw/. Placeholder assigned.",
    description: "Regional leaf tea powder pack.",
    rating: 4.8,
    reviewsCount: 17,
    isPopular: true,
    is_ambiguous: true,
    ambiguity_note: "Regional tea pack. Needs exact package photo from store."
  },
  {
    id: "g1-4",
    itemNumber: 4,
    rawName: "50-50 SWEET&SALTY",
    cleanName: "Britannia 50-50 Sweet & Salty Biscuits",
    brand: "Britannia",
    category: "snacks",
    subCategory: "Biscuits & Cookies",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size unstated in POS. Placeholder assigned.",
    description: "Light and crispy sweet & salty biscuits.",
    rating: 4.8,
    reviewsCount: 18,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Pack weight missing in POS (could be 45g, 65g, or 120g)."
  },
  {
    id: "g1-5",
    itemNumber: 5,
    rawName: "707 SOAP",
    cleanName: "707 Soap Bar",
    brand: "707",
    category: "household",
    subCategory: "Detergent & Fabric Care",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Ambiguous entry. Laundry soap or bath bar not specified. Placeholder assigned.",
    description: "Soap bar from G1 Mart inventory.",
    rating: 4.8,
    reviewsCount: 19,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Ambiguous soap type and weight."
  },
  {
    id: "g1-6",
    itemNumber: 6,
    rawName: "AACHHI GARAM MASALA",
    cleanName: "Aachi Garam Masala Powder",
    brand: "Aachi",
    category: "edible-oils",
    subCategory: "Spices & Masalas",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack weight missing in POS. Placeholder assigned.",
    description: "Aromatic blend of ground Indian spices.",
    rating: 4.8,
    reviewsCount: 20,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Pack weight not specified (50g vs 100g)."
  },
  {
    id: "g1-7",
    itemNumber: 7,
    rawName: "AACHI APPALAM 100G",
    cleanName: "Aachi Appalam (100 g)",
    brand: "Aachi",
    category: "snacks",
    subCategory: "Papads & Fryums",
    unit: "100 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Exact pack size known. Awaiting photo in /product-photos-raw/.",
    description: "Crispy South Indian style appalam.",
    rating: 4.8,
    reviewsCount: 21,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-8",
    itemNumber: 8,
    rawName: "AACHI CHICKEN MASALA",
    cleanName: "Aachi Chicken Masala Powder",
    brand: "Aachi",
    category: "edible-oils",
    subCategory: "Spices & Masalas",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack weight missing in POS.",
    description: "Traditional spice mix for chicken curries.",
    rating: 4.8,
    reviewsCount: 22,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Pack weight missing."
  },
  {
    id: "g1-9",
    itemNumber: 9,
    rawName: "Aashirvaad 1kg",
    cleanName: "Aashirvaad 1kg (Variant Unspecified)",
    brand: "Aashirvaad",
    category: "rice-dal-atta",
    subCategory: "Atta & Flours",
    unit: "1 kg",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 33,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Ambiguous variant. Could be Whole Wheat Atta, Multi-grain, or Salt. Placeholder enforced.",
    description: "1kg pack from Aashirvaad.",
    rating: 4.8,
    reviewsCount: 23,
    isPopular: true,
    is_ambiguous: true,
    ambiguity_note: "Variant not specified (Atta vs Salt vs Flours)."
  },
  {
    id: "g1-10",
    itemNumber: 10,
    rawName: "AASHIRVAAD CRYSTAL SALT 1KG",
    cleanName: "Aashirvaad Crystal Salt (1 kg)",
    brand: "Aashirvaad",
    category: "rice-dal-atta",
    subCategory: "Salt & Sugar",
    unit: "1 kg",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 15,
    image: "/products/placeholder.svg",
    image_path: "/products/prod-1.jpg",
    image_source: "manufacturer",
    image_license: "Proprietary Brand Pack",
    image_status: "pending",
    image_match_note: "Candidate photo matches Aashirvaad salt pack. Pending user review.",
    description: "Pure solar-evaporated crystal salt.",
    rating: 4.8,
    reviewsCount: 24,
    isPopular: true,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-11",
    itemNumber: 11,
    rawName: "AASHIRVAAD SALT",
    cleanName: "Aashirvaad Iodised Salt",
    brand: "Aashirvaad",
    category: "rice-dal-atta",
    subCategory: "Salt & Sugar",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 12,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size missing in POS.",
    description: "Refined iodised salt.",
    rating: 4.8,
    reviewsCount: 25,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Pack size missing in POS entry."
  },
  {
    id: "g1-12",
    itemNumber: 12,
    rawName: "Aashirvaad Suji Rava",
    cleanName: "Aashirvaad Suji Rava",
    brand: "Aashirvaad",
    category: "rice-dal-atta",
    subCategory: "Atta & Flours",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 21,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size missing in POS.",
    description: "Finely milled semolina suji rava.",
    rating: 4.8,
    reviewsCount: 26,
    isPopular: true,
    is_ambiguous: true,
    ambiguity_note: "Pack weight (500g or 1kg) missing in POS."
  },
  {
    id: "g1-13",
    itemNumber: 13,
    rawName: "Aashirvaad Vermicelli",
    cleanName: "Aashirvaad Vermicelli",
    brand: "Aashirvaad",
    category: "rice-dal-atta",
    subCategory: "Rice & Grains",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size missing in POS.",
    description: "Wheat vermicelli for upma and payasam.",
    rating: 4.8,
    reviewsCount: 27,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Pack weight missing."
  },
  {
    id: "g1-14",
    itemNumber: 14,
    rawName: "AASHIRVAAD VERMICELLI 850G",
    cleanName: "Aashirvaad Roasted Vermicelli (850 g)",
    brand: "Aashirvaad",
    category: "rice-dal-atta",
    subCategory: "Rice & Grains",
    unit: "850 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Exact weight known. Awaiting photo in /product-photos-raw/.",
    description: "Pre-roasted vermicelli pack.",
    rating: 4.8,
    reviewsCount: 28,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-15",
    itemNumber: 15,
    rawName: "ACID 700ML",
    cleanName: "Cleaning Muriatic Acid (700 ml)",
    brand: "Unstated",
    category: "household",
    subCategory: "Floor & Cleaners",
    unit: "700 ml",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Generic cleaning acid. Brand unstated.",
    description: "Heavy duty toilet and floor cleaning acid.",
    rating: 4.8,
    reviewsCount: 29,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Manufacturer/brand unstated."
  },
  {
    id: "g1-16",
    itemNumber: 16,
    rawName: "Ajay Brush",
    cleanName: "Ajay Toothbrush",
    brand: "Ajay",
    category: "personal-care",
    subCategory: "Oral Care",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 12,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Specific variant unstated.",
    description: "Manual toothbrush with round end bristles.",
    rating: 4.8,
    reviewsCount: 30,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Bristle variant (Medium / Soft / Hard) not stated."
  },
  {
    id: "g1-17",
    itemNumber: 17,
    rawName: "ALL IN ONE 100G",
    cleanName: "All In One (100 g)",
    brand: "Unstated",
    category: "household",
    subCategory: "Home Utilities & Stationery",
    unit: "100 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Cryptic cashier name. Product identity unverified.",
    description: "Product from G1 Mart inventory.",
    rating: 4.8,
    reviewsCount: 31,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Cryptic entry: could be namkeen mixture, spice blend, or home cleaning powder."
  },
  {
    id: "g1-18",
    itemNumber: 18,
    rawName: "ALLOUT MATCHS",
    cleanName: "Allout / Matches Entry",
    brand: "Unstated",
    category: "household",
    subCategory: "Home Utilities & Stationery",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Conflicting cashier entry. Placeholder assigned.",
    description: "Item from G1 Mart inventory.",
    rating: 4.8,
    reviewsCount: 32,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Conflicting entry: combines 'Allout' (mosquito repellent) with 'MATCHS'."
  },
  {
    id: "g1-19",
    itemNumber: 19,
    rawName: "APSARA PENCILS",
    cleanName: "Apsara Platinum Extra Dark Pencils",
    brand: "Apsara",
    category: "household",
    subCategory: "Home Utilities & Stationery",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Awaiting photo upload into /product-photos-raw/.",
    description: "High quality dark writing pencils pack.",
    rating: 4.8,
    reviewsCount: 33,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-20",
    itemNumber: 20,
    rawName: "ARIEL FRONT LIQ 10",
    cleanName: "Ariel Matic Front Load Liquid Detergent (₹10 Sachet)",
    brand: "Ariel",
    category: "household",
    subCategory: "Detergent & Fabric Care",
    unit: "1 piece",
    price: 10,
    priceConfirmed: true,
    originalPrice: 10,
    discountPercentage: 0,
    inStock: true,
    stockCount: 48,
    image: "/products/placeholder.svg",
    image_path: "/products/prod-9.jpg",
    image_source: "manufacturer",
    image_license: "Proprietary Brand Pack",
    image_status: "pending",
    image_match_note: "Candidate pack image matches Ariel Matic Front Load pack. Pending user review.",
    description: "Liquid detergent sachet formulated for front load washing machines.",
    rating: 4.8,
    reviewsCount: 34,
    isPopular: true,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-21",
    itemNumber: 21,
    rawName: "Ariel Power Gel Top Load&semi Auto 1kg",
    cleanName: "Ariel Matic Power Gel Top Load & Semi-Auto (1 kg)",
    brand: "Ariel",
    category: "household",
    subCategory: "Detergent & Fabric Care",
    unit: "1 kg",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Exact bottle photo not in /product-photos-raw/.",
    description: "Tough stain removal gel for top load machines.",
    rating: 4.8,
    reviewsCount: 35,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-22",
    itemNumber: 22,
    rawName: "AROKYA MILK",
    cleanName: "Arokya Fresh Toned Milk Pouch",
    brand: "Arokya",
    category: "dairy-bakery",
    subCategory: "Milk & Curd",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack volume missing in POS.",
    description: "Pasteurised toned milk from Arokya.",
    rating: 4.8,
    reviewsCount: 36,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Pouch size (500ml vs 1L) unstated."
  },
  {
    id: "g1-23",
    itemNumber: 23,
    rawName: "ARUN BITES",
    cleanName: "Arun Icecream Bites",
    brand: "Arun Icecreams",
    category: "dairy-bakery",
    subCategory: "Ice Creams & Frozen Treats",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 63,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Zero guessing: placeholder enforced until exact wrapper photo uploaded.",
    description: "Bite-sized chocolate coated ice cream treat.",
    rating: 4.8,
    reviewsCount: 37,
    isPopular: true,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-24",
    itemNumber: 24,
    rawName: "ARUN DONUT",
    cleanName: "Arun Icecream Donut Bar",
    brand: "Arun Icecreams",
    category: "dairy-bakery",
    subCategory: "Ice Creams & Frozen Treats",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 60,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Placeholder enforced.",
    description: "Donut shaped novelty ice cream bar.",
    rating: 4.8,
    reviewsCount: 38,
    isPopular: true,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-25",
    itemNumber: 25,
    rawName: "ARUN DOUBLE",
    cleanName: "Arun Icecream Double Bar",
    brand: "Arun Icecreams",
    category: "dairy-bakery",
    subCategory: "Ice Creams & Frozen Treats",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Placeholder enforced.",
    description: "Twin flavoured ice cream bar.",
    rating: 4.8,
    reviewsCount: 39,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-26",
    itemNumber: 26,
    rawName: "ARUN IBAR",
    cleanName: "Arun Icecream i-Bar Stick",
    brand: "Arun Icecreams",
    category: "dairy-bakery",
    subCategory: "Ice Creams & Frozen Treats",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Placeholder enforced.",
    description: "Premium ice cream stick bar.",
    rating: 4.8,
    reviewsCount: 40,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-27",
    itemNumber: 27,
    rawName: "ARUN MILKY FANTASY",
    cleanName: "Arun Icecream Milky Fantasy Stick",
    brand: "Arun Icecreams",
    category: "dairy-bakery",
    subCategory: "Ice Creams & Frozen Treats",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Placeholder enforced.",
    description: "Rich milky white ice cream stick bar.",
    rating: 4.8,
    reviewsCount: 41,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-28",
    itemNumber: 28,
    rawName: "Arun Popitos",
    cleanName: "Arun Icecream Popitos",
    brand: "Arun Icecreams",
    category: "dairy-bakery",
    subCategory: "Ice Creams & Frozen Treats",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 18,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Placeholder enforced.",
    description: "Mini ice cream pop treat.",
    rating: 4.8,
    reviewsCount: 42,
    isPopular: true,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-29",
    itemNumber: 29,
    rawName: "Arun Sunny Sil",
    cleanName: "Arun Icecream Sunny Slice / Silver",
    brand: "Arun Icecreams",
    category: "dairy-bakery",
    subCategory: "Ice Creams & Frozen Treats",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Abbreviated entry in POS. Placeholder enforced.",
    description: "Ice cream slice treat.",
    rating: 4.8,
    reviewsCount: 43,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Abbreviated variant 'Sunny Sil' in POS report."
  },
  {
    id: "g1-30",
    itemNumber: 30,
    rawName: "ARUN TOFFEE CON",
    cleanName: "Arun Icecream Toffee Cone",
    brand: "Arun Icecreams",
    category: "dairy-bakery",
    subCategory: "Ice Creams & Frozen Treats",
    unit: "1 piece",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 18,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Placeholder enforced.",
    description: "Crispy waffle cone filled with toffee ice cream.",
    rating: 4.8,
    reviewsCount: 44,
    isPopular: true,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-31",
    itemNumber: 31,
    rawName: "ASSORATED FRUIT",
    cleanName: "Assorted Fruit Item",
    brand: "Unstated",
    category: "fruits-vegetables",
    subCategory: "Fresh Produce & Fruits",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Highly ambiguous product identity. Placeholder assigned.",
    description: "Product from G1 Mart inventory.",
    rating: 4.8,
    reviewsCount: 45,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Ambiguous entry: could be confectionery fruit chews, fruit jam, or fresh fruits."
  },
  {
    id: "g1-32",
    itemNumber: 32,
    rawName: "Avalu 250g",
    cleanName: "Mustard Seeds / Avalu (250 g)",
    brand: "G1 Mart Store-Packed",
    category: "edible-oils",
    subCategory: "Whole Spices & Seeds",
    unit: "250 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Store-packed grain. Awaiting physical pack photo upload.",
    description: "Clean black mustard seeds (avalu).",
    rating: 4.8,
    reviewsCount: 46,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-33",
    itemNumber: 33,
    rawName: "Avalu50g",
    cleanName: "Mustard Seeds / Avalu (50 g)",
    brand: "G1 Mart Store-Packed",
    category: "edible-oils",
    subCategory: "Whole Spices & Seeds",
    unit: "50 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Store-packed grain. Awaiting photo.",
    description: "Clean black mustard seeds (avalu).",
    rating: 4.8,
    reviewsCount: 47,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-34",
    itemNumber: 34,
    rawName: "BADAM 100GR",
    cleanName: "Whole Almonds / Badam (100 g)",
    brand: "G1 Mart Store-Packed",
    category: "snacks",
    subCategory: "Dry Fruits & Nuts",
    unit: "100 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Store-packed dry fruit. Awaiting photo in /product-photos-raw/.",
    description: "Premium California whole almonds.",
    rating: 4.8,
    reviewsCount: 48,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-35",
    itemNumber: 35,
    rawName: "BADAM 250G",
    cleanName: "Whole Almonds / Badam (250 g)",
    brand: "G1 Mart Store-Packed",
    category: "snacks",
    subCategory: "Dry Fruits & Nuts",
    unit: "250 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Store-packed dry fruit. Awaiting photo in /product-photos-raw/.",
    description: "Premium California whole almonds.",
    rating: 4.8,
    reviewsCount: 49,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-36",
    itemNumber: 36,
    rawName: "BADAM 50G",
    cleanName: "Whole Almonds / Badam (50 g)",
    brand: "G1 Mart Store-Packed",
    category: "snacks",
    subCategory: "Dry Fruits & Nuts",
    unit: "50 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Store-packed dry fruit. Awaiting photo in /product-photos-raw/.",
    description: "Premium California whole almonds.",
    rating: 4.8,
    reviewsCount: 50,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-37",
    itemNumber: 37,
    rawName: "BAMBINO MYSORE PACK 200G",
    cleanName: "Bambino Mysore Pak Sweet Box (200 g)",
    brand: "Bambino",
    category: "snacks",
    subCategory: "Chocolates & Sweets",
    unit: "200 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Sweet box photo not in /product-photos-raw/.",
    description: "Traditional melt-in-mouth Mysore Pak sweet box.",
    rating: 4.8,
    reviewsCount: 51,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-38",
    itemNumber: 38,
    rawName: "BAMBINON VERMICELLI 250G",
    cleanName: "Bambino Roasted Vermicelli (250 g)",
    brand: "Bambino",
    category: "rice-dal-atta",
    subCategory: "Rice & Grains",
    unit: "250 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack photo not in /product-photos-raw/.",
    description: "Pre-roasted short cut vermicelli.",
    rating: 4.8,
    reviewsCount: 52,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-39",
    itemNumber: 39,
    rawName: "BANSI RAVA 500G",
    cleanName: "Bansi Rava (500 g)",
    brand: "G1 Mart Store-Packed",
    category: "rice-dal-atta",
    subCategory: "Atta & Flours",
    unit: "500 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Store-packed staple. Awaiting pack photo.",
    description: "Coarsely ground whole wheat bansi rava.",
    rating: 4.8,
    reviewsCount: 53,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-40",
    itemNumber: 40,
    rawName: "BAT PAPAD 250G",
    cleanName: "Bat Papad (250 g)",
    brand: "Unstated",
    category: "snacks",
    subCategory: "Papads & Fryums",
    unit: "250 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Brand unstated.",
    description: "Bat shaped crispy fryums / papad.",
    rating: 4.8,
    reviewsCount: 54,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Manufacturer/brand unstated."
  },
  {
    id: "g1-41",
    itemNumber: 41,
    rawName: "BINGO CHILLI",
    cleanName: "Bingo Mad Angles Chilli Sprinkles",
    brand: "Bingo",
    category: "snacks",
    subCategory: "Chips & Namkeen",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 36,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size unstated in POS.",
    description: "Crunchy triangle chips with spicy chilli seasoning.",
    rating: 4.8,
    reviewsCount: 55,
    isPopular: true,
    is_ambiguous: true,
    ambiguity_note: "Pack weight unstated in POS."
  },
  {
    id: "g1-42",
    itemNumber: 42,
    rawName: "BINGO KOREAN",
    cleanName: "Bingo Korean Spicy Potato Chips",
    brand: "Bingo",
    category: "snacks",
    subCategory: "Chips & Namkeen",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size unstated in POS.",
    description: "Spicy Korean style potato chips.",
    rating: 4.8,
    reviewsCount: 56,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Pack weight unstated in POS."
  },
  {
    id: "g1-43",
    itemNumber: 43,
    rawName: "BINGO MASALA",
    cleanName: "Bingo Mad Angles Masala Madness",
    brand: "Bingo",
    category: "snacks",
    subCategory: "Chips & Namkeen",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 15,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size unstated in POS.",
    description: "Crunchy triangle chips with chatpata masala flavour.",
    rating: 4.8,
    reviewsCount: 57,
    isPopular: true,
    is_ambiguous: true,
    ambiguity_note: "Pack weight unstated in POS."
  },
  {
    id: "g1-44",
    itemNumber: 44,
    rawName: "BINGO MASTI",
    cleanName: "Bingo Tedhe Medhe Masala Tadka / Masti",
    brand: "Bingo",
    category: "snacks",
    subCategory: "Chips & Namkeen",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 15,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size unstated in POS.",
    description: "Spicy curved corn snack sticks.",
    rating: 4.8,
    reviewsCount: 58,
    isPopular: true,
    is_ambiguous: true,
    ambiguity_note: "Pack weight unstated in POS."
  },
  {
    id: "g1-45",
    itemNumber: 45,
    rawName: "BINGO TOMATO",
    cleanName: "Bingo Mad Angles Tomato Madness",
    brand: "Bingo",
    category: "snacks",
    subCategory: "Chips & Namkeen",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size unstated in POS.",
    description: "Tangy tomato flavoured triangle chips.",
    rating: 4.8,
    reviewsCount: 59,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Pack weight unstated in POS."
  },
  {
    id: "g1-46",
    itemNumber: 46,
    rawName: "BINO TEMATO 21G",
    cleanName: "Bingo Mad Angles Tomato Madness (21 g)",
    brand: "Bingo",
    category: "snacks",
    subCategory: "Chips & Namkeen",
    unit: "21 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 21,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Exact 21g pack known. Awaiting photo in /product-photos-raw/.",
    description: "Tangy tomato flavoured triangle chips (21 g pocket pack).",
    rating: 4.8,
    reviewsCount: 60,
    isPopular: true,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-47",
    itemNumber: 47,
    rawName: "Biriyani Masala",
    cleanName: "Biryani Masala Powder",
    brand: "Unstated",
    category: "edible-oils",
    subCategory: "Spices & Masalas",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Brand and pack size both missing. Flagged for review.",
    description: "Aromatic biryani masala powder.",
    rating: 4.8,
    reviewsCount: 61,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Brand and pack weight both missing in POS record."
  },
  {
    id: "g1-48",
    itemNumber: 48,
    rawName: "BISCOTT",
    cleanName: "Biscotti / Biscuit Item",
    brand: "Unstated",
    category: "snacks",
    subCategory: "Biscuits & Cookies",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Cryptic cashier abbreviation. Product identity unverified.",
    description: "Item from G1 Mart inventory.",
    rating: 4.8,
    reviewsCount: 62,
    isPopular: false,
    is_ambiguous: true,
    ambiguity_note: "Cryptic cashier abbreviation 'BISCOTT'. Brand and pack unspecified."
  },
  {
    id: "g1-49",
    itemNumber: 49,
    rawName: "BLEACHUNG POWDER 100G",
    cleanName: "Disinfectant Bleaching Powder (100 g)",
    brand: "G1 Mart Store-Packed",
    category: "household",
    subCategory: "Floor & Cleaners",
    unit: "100 g",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 10,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Store-packed disinfectant. Awaiting physical pack photo.",
    description: "Household sanitation and water disinfectant bleaching powder.",
    rating: 4.8,
    reviewsCount: 63,
    isPopular: false,
    is_ambiguous: false,
    ambiguity_note: undefined
  },
  {
    id: "g1-50",
    itemNumber: 50,
    rawName: "BOOST",
    cleanName: "Boost Chocolate Health Drink",
    brand: "Boost",
    category: "beverages",
    subCategory: "Health Drinks",
    unit: "1 pack",
    price: 0,
    priceConfirmed: false,
    originalPrice: 0,
    discountPercentage: 0,
    inStock: true,
    stockCount: 93,
    image: "/products/placeholder.svg",
    image_path: undefined,
    image_source: "placeholder",
    image_license: null,
    image_status: "placeholder",
    image_match_note: "Pack size unstated in POS.",
    description: "Malted chocolate nutritional drink mix.",
    rating: 4.8,
    reviewsCount: 64,
    isPopular: true,
    is_ambiguous: true,
    ambiguity_note: "Pack weight unstated (could be 200g, 500g, or 1kg)."
  }
];

// Combine pilot items with clean formatted catalog items
// Map existing products into catalog.ts with placeholder default unless approved
const tsProducts = pilotCatalog.map(p => ({
  id: p.id,
  itemNumber: p.itemNumber,
  rawName: p.rawName,
  name: p.cleanName,
  brand: p.brand,
  category: p.category,
  subCategory: p.subCategory,
  unit: p.unit,
  price: p.price,
  priceConfirmed: p.priceConfirmed,
  originalPrice: p.originalPrice,
  discountPercentage: p.discountPercentage,
  inStock: p.inStock,
  stockCount: p.stockCount,
  image: "/products/placeholder.svg", // STRICT: Storefront always renders placeholder unless approved
  image_path: p.image_path,
  image_source: p.image_source,
  image_license: p.image_license,
  image_status: p.image_status,
  image_match_note: p.image_match_note,
  description: p.description,
  rating: p.rating,
  reviewsCount: p.reviewsCount,
  isPopular: p.isPopular,
  isBestDeal: false,
  is_ambiguous: p.is_ambiguous,
  ambiguity_note: p.ambiguity_note
}));

// Save to src/data/catalog.ts
const catalogPath = path.join(__dirname, '..', 'src', 'data', 'catalog.ts');
const catalogTsContent = `/**
 * G1 MART — Pilot Catalogue (50 Items)
 * Strict Section 9.2 Compliance:
 * - Approved-only image rendering (storefront displays official placeholder)
 * - Zero stock photo guessing
 * - Ambiguous names flagged for store review
 * - Unconfirmed prices left as TBA (priceConfirmed: false)
 */
import type { Product } from '@/types';

export const CATALOG_PRODUCTS: Product[] = ${JSON.stringify(tsProducts, null, 2)};
`;

fs.writeFileSync(catalogPath, catalogTsContent, 'utf8');
console.log(`Saved src/data/catalog.ts with ${tsProducts.length} pilot products.`);

// Generate docs/image-review.html contact sheet
const reviewHtmlPath = path.join(__dirname, '..', 'docs', 'image-review.html');

const rowsHtml = pilotCatalog.map(p => {
  const isCandidate = p.image_path !== undefined;
  const imgTag = isCandidate
    ? `<img src="${p.image_path}" alt="${p.cleanName}" style="max-height: 120px; max-width: 120px; object-fit: contain; border-radius: 8px; border: 1px solid #e2e8f0; padding: 4px; background: #fff;" />`
    : `<img src="/products/placeholder.svg" alt="Placeholder" style="max-height: 120px; max-width: 120px; object-fit: contain; border-radius: 8px; border: 1px dashed #cbd5e1; padding: 4px; background: #f8fafc;" />`;

  const statusBadge = p.image_status === 'approved'
    ? `<span style="background: #dcfce7; color: #15803d; font-weight: 700; padding: 3px 8px; border-radius: 6px; font-size: 11px;">APPROVED</span>`
    : p.image_status === 'pending'
    ? `<span style="background: #fef9c3; color: #854d0e; font-weight: 700; padding: 3px 8px; border-radius: 6px; font-size: 11px;">PENDING REVIEW</span>`
    : `<span style="background: #f1f5f9; color: #475569; font-weight: 700; padding: 3px 8px; border-radius: 6px; font-size: 11px;">PLACEHOLDER</span>`;

  const ambiguityBadge = p.is_ambiguous
    ? `<span style="background: #fee2e2; color: #b91c1c; font-weight: 700; padding: 2px 6px; border-radius: 4px; font-size: 10px; display: inline-block; margin-top: 4px;">⚠️ AMBIGUOUS</span>`
    : `<span style="background: #e0f2fe; color: #0369a1; font-weight: 700; padding: 2px 6px; border-radius: 4px; font-size: 10px; display: inline-block; margin-top: 4px;">✓ CLEAR</span>`;

  return `
    <tr style="border-bottom: 1px solid #f1f5f9; background: ${p.is_ambiguous ? '#fffdf7' : '#ffffff'};">
      <td style="padding: 12px; font-mono; font-size: 11px; color: #64748b;">#${p.itemNumber}</td>
      <td style="padding: 12px;">
        <div style="font-weight: 700; color: #0f172a; font-size: 13px;">${p.cleanName}</div>
        <div style="font-size: 11px; color: #64748b; margin-top: 2px;">POS Raw: <code>${p.rawName}</code></div>
        <div style="font-size: 11px; color: #475569;">Brand: <strong>${p.brand}</strong> · Unit: <strong>${p.unit}</strong></div>
        ${ambiguityBadge}
        ${p.ambiguity_note ? `<div style="font-size: 11px; color: #b91c1c; margin-top: 2px;">Note: ${p.ambiguity_note}</div>` : ''}
      </td>
      <td style="padding: 12px; text-align: center;">
        ${imgTag}
      </td>
      <td style="padding: 12px; font-size: 12px;">
        <div style="font-weight: 600; color: #334155;">${p.image_source}</div>
        <div style="font-size: 10px; color: #94a3b8; margin-top: 2px;">${p.image_license || 'No license required'}</div>
      </td>
      <td style="padding: 12px; font-size: 12px; color: #334155; max-width: 260px;">
        ${p.image_match_note}
      </td>
      <td style="padding: 12px; text-align: center;">
        ${statusBadge}
      </td>
      <td style="padding: 12px; text-align: center; white-space: nowrap;">
        <button onclick="alert('Action recorded: User decision needed for #${p.itemNumber}')" style="cursor: pointer; padding: 6px 12px; font-size: 11px; font-weight: 700; background: #2E7D32; color: #fff; border: none; border-radius: 6px; margin-right: 4px;">Approve</button>
        <button onclick="alert('Action recorded: Rejected #${p.itemNumber}')" style="cursor: pointer; padding: 6px 12px; font-size: 11px; font-weight: 700; background: #dc2626; color: #fff; border: none; border-radius: 6px;">Reject</button>
      </td>
    </tr>
  `;
}).join('\n');

const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>G1 Mart — Catalogue Image Review Contact Sheet (Section 9.2)</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background: #f8fafc; color: #0f172a; margin: 0; padding: 24px; }
    .container { max-width: 1200px; margin: 0 auto; background: #ffffff; border-radius: 16px; border: 1px solid #e2e8f0; box-shadow: 0 1px 3px rgba(0,0,0,0.05); overflow: hidden; }
    .header { padding: 24px; background: #1a2e1c; color: #ffffff; }
    .header h1 { margin: 0 0 8px 0; font-size: 20px; font-weight: 800; display: flex; align-items: center; gap: 8px; }
    .header p { margin: 0; font-size: 13px; color: #cbd5e1; line-height: 1.5; }
    .stats { display: flex; gap: 16px; padding: 16px 24px; background: #f1f5f9; border-bottom: 1px solid #e2e8f0; font-size: 12px; font-weight: 600; flex-wrap: wrap; }
    .stat-badge { background: #ffffff; border: 1px solid #cbd5e1; padding: 6px 12px; border-radius: 8px; }
    .stat-badge strong { color: #0f172a; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; text-align: left; }
    th { padding: 12px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; font-weight: 700; background: #f8fafc; border-bottom: 2px solid #e2e8f0; }
    code { font-family: monospace; background: #f1f5f9; padding: 2px 4px; border-radius: 4px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>G1 Mart — Catalogue Image Review Contact Sheet</h1>
      <p>Strict Section 9.2 Compliance Review Gate. Only store owner approvals can change image status from <em>pending</em> to <em>approved</em>. The storefront displays official placeholders for all unapproved items.</p>
    </div>

    <div class="stats">
      <div class="stat-badge">Total Pilot Products: <strong>${pilotCatalog.length}</strong></div>
      <div class="stat-badge" style="border-left: 3px solid #b91c1c;">Ambiguous Names Flagged: <strong>${pilotCatalog.filter(p => p.is_ambiguous).length}</strong></div>
      <div class="stat-badge" style="border-left: 3px solid #f59e0b;">Candidate Matches (Pending Review): <strong>${pilotCatalog.filter(p => p.image_status === 'pending').length}</strong></div>
      <div class="stat-badge" style="border-left: 3px solid #64748b;">Enforced Placeholders: <strong>${pilotCatalog.filter(p => p.image_status === 'placeholder').length}</strong></div>
      <div class="stat-badge" style="border-left: 3px solid #16a34a;">Storefront Display: <strong>100% Placeholders (Safe)</strong></div>
    </div>

    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Product Name &amp; POS Details</th>
          <th style="text-align: center;">Candidate Image</th>
          <th>Source &amp; License</th>
          <th>Why it Matches / Ambiguity Note</th>
          <th style="text-align: center;">Status</th>
          <th style="text-align: center;">Review Gate Action</th>
        </tr>
      </thead>
      <tbody>
        ${rowsHtml}
      </tbody>
    </table>
  </div>
</body>
</html>
`;

fs.writeFileSync(reviewHtmlPath, htmlContent, 'utf8');
console.log(`Saved docs/image-review.html contact sheet with ${pilotCatalog.length} rows.`);

// Report summary
const ambiguousCount = pilotCatalog.filter(p => p.is_ambiguous).length;
const pendingCount = pilotCatalog.filter(p => p.image_status === 'pending').length;
const placeholderCount = pilotCatalog.filter(p => p.image_status === 'placeholder').length;

console.log('\n--- PILOT REPORT ---');
console.log(`Total Pilot Products: ${pilotCatalog.length}`);
console.log(`Candidate Matches Pending Review: ${pendingCount}`);
console.log(`Placeholders Enforced: ${placeholderCount}`);
console.log(`Ambiguous Names Flagged: ${ambiguousCount}`);
