-- =============================================================================
-- G1 MART — Product Master Seed (472 Items from Sales Detail PDF)
-- All imported products have:
--   image_url = NULL, image_status = 'MISSING', active = true,
--   price = NULL, original_price = NULL, stock_count = NULL (until verified).
-- Preserves existing database records and verified product images.
-- Ensure is_active column exists
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

INSERT INTO public.products (
  id,
  source_item_no,
  source_name,
  name,
  brand,
  category_id,
  variant,
  unit,
  price,
  original_price,
  stock_count,
  discount_percentage,
  in_stock,
  image_url,
  image_status,
  description,
  rating,
  reviews_count,
  is_popular,
  is_best_deal,
  is_active,
  active
) VALUES
('g1-prod-001', 1, '5 MUCH', '5 MUCH', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-002', 2, '5 STAR 5RS', '5 STAR 5RS', NULL, 'snacks', '5RS', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-003', 3, '5 Star Tea 250g', '5 Star Tea 250g', NULL, 'beverages', '250g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-004', 4, '50-50 SWEET&SALTY', '50-50 SWEET&SALTY', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-005', 5, '707 SOAP', '707 SOAP', NULL, 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-006', 6, 'AACHHI GARAM MASALA', 'AACHHI GARAM MASALA', 'Aachi', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-007', 7, 'AACHI APPALAM 100G', 'AACHI APPALAM 100G', 'Aachi', 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-008', 8, 'AACHI CHICKEN MASALA', 'AACHI CHICKEN MASALA', 'Aachi', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-009', 9, 'Aashirvaad 1kg', 'Aashirvaad 1kg', 'Aashirvaad', NULL, '1kg', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-010', 10, 'AASHIRVAAD CRYSTAL SALT 1KG', 'AASHIRVAAD CRYSTAL SALT 1KG', 'Aashirvaad', 'rice-dal-atta', '1KG', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-011', 11, 'AASHIRVAAD SALT', 'AASHIRVAAD SALT', 'Aashirvaad', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-012', 12, 'Aashirvaad Suji Rava', 'Aashirvaad Suji Rava', 'Aashirvaad', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-013', 13, 'Aashirvaad Vermicelli', 'Aashirvaad Vermicelli', 'Aashirvaad', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-014', 14, 'AASHIRVAAD VERMICELLI 850G', 'AASHIRVAAD VERMICELLI 850G', 'Aashirvaad', 'rice-dal-atta', '850G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-015', 15, 'ACID 700ML', 'ACID 700ML', NULL, NULL, '700ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-016', 16, 'Ajay Brush', 'Ajay Brush', 'Ajay', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-017', 17, 'ALL IN ONE 100G', 'ALL IN ONE 100G', NULL, NULL, '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-018', 18, 'ALLOUT MATCHS', 'ALLOUT MATCHS', 'All Out', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-019', 19, 'APSARA PENCILS', 'APSARA PENCILS', 'Apsara', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-020', 20, 'ARIEL FRONT LIQ 10', 'ARIEL FRONT LIQ 10', 'Ariel', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-021', 21, 'Ariel Power Gel Top Load&semi Auto 1kg', 'Ariel Power Gel Top Load&semi Auto 1kg', 'Ariel', NULL, '1kg', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-022', 22, 'AROKYA MILK', 'AROKYA MILK', 'Arokya', 'dairy-bakery', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-023', 23, 'ARUN BITES', 'ARUN BITES', 'Arun', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-024', 24, 'ARUN DONUT', 'ARUN DONUT', 'Arun', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-025', 25, 'ARUN DOUBLE', 'ARUN DOUBLE', 'Arun', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-026', 26, 'ARUN IBAR', 'ARUN IBAR', 'Arun', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-027', 27, 'ARUN MILKY FANTASY', 'ARUN MILKY FANTASY', 'Arun', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-028', 28, 'Arun Popitos', 'Arun Popitos', 'Arun', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-029', 29, 'Arun Sunny Sil', 'Arun Sunny Sil', 'Arun', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-030', 30, 'ARUN TOFFEE CON', 'ARUN TOFFEE CON', 'Arun', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-031', 31, 'ASSORATED FRUIT', 'ASSORATED FRUIT', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-032', 32, 'Avalu 250g', 'Avalu 250g', NULL, 'rice-dal-atta', '250g', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-033', 33, 'Avalu50g', 'Avalu50g', NULL, NULL, NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-034', 34, 'BADAM 100GR', 'BADAM 100GR', NULL, 'rice-dal-atta', '100GR', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-035', 35, 'BADAM 250G', 'BADAM 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-036', 36, 'BADAM 50G', 'BADAM 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-037', 37, 'BAMBINO MYSORE PACK 200G', 'BAMBINO MYSORE PACK 200G', 'Bambino', 'snacks', '200G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-038', 38, 'BAMBINON VERMICELLI 250G', 'BAMBINON VERMICELLI 250G', 'Bambino', 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-039', 39, 'BANSI RAVA 500G', 'BANSI RAVA 500G', NULL, 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-040', 40, 'BAT PAPAD 250G', 'BAT PAPAD 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-041', 41, 'BINGO CHILLI', 'BINGO CHILLI', 'Bingo', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-042', 42, 'BINGO KOREAN', 'BINGO KOREAN', 'Bingo', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-043', 43, 'BINGO MASALA', 'BINGO MASALA', 'Bingo', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-044', 44, 'BINGO MASTI', 'BINGO MASTI', 'Bingo', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-045', 45, 'BINGO TOMATO', 'BINGO TOMATO', 'Bingo', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-046', 46, 'BINO TEMATO 21G', 'BINO TEMATO 21G', 'Bingo', NULL, '21G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-047', 47, 'Biriyani Masala', 'Biriyani Masala', NULL, 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-048', 48, 'BISCOTT', 'BISCOTT', NULL, 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-049', 49, 'BLEACHUNG POWDER 100G', 'BLEACHUNG POWDER 100G', NULL, 'household', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-050', 50, 'BOOST', 'BOOST', 'Boost', 'beverages', NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-051', 51, 'BOOST 200G', 'BOOST 200G', 'Boost', 'beverages', '200G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-052', 52, 'BOURBON BISCUIT', 'BOURBON BISCUIT', 'Bourbon', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-053', 53, 'BRU', 'BRU', 'Bru', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-054', 54, 'Bru Instant 1.2g', 'Bru Instant 1.2g', 'Bru', 'beverages', '1.2g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-055', 55, 'BRU INSTENT JAR', 'BRU INSTENT JAR', 'Bru', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-056', 56, 'Brush', 'Brush', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-057', 57, 'CAMLIN 0.7MM LEDIS', 'CAMLIN 0.7MM LEDIS', 'Camlin', NULL, '7MM', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-058', 58, 'Camphor 50g', 'Camphor 50g', NULL, 'household', '50g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-059', 59, 'CASTOR OIL 100ML', 'CASTOR OIL 100ML', NULL, 'rice-dal-atta', '100ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-060', 60, 'CHILLY POWDER 100G', 'CHILLY POWDER 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-061', 61, 'CHOKI STIX 16G', 'CHOKI STIX 16G', NULL, 'snacks', '16G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-062', 62, 'CINTHOL', 'CINTHOL', 'Cinthol', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-063', 63, 'CLASSIC RUSK 59G', 'CLASSIC RUSK 59G', NULL, 'dairy-bakery', '59G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-064', 64, 'Cleaning Wiper', 'Cleaning Wiper', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-065', 65, 'CLEAR ANTI-DANDRUFF NUTRIUM', 'CLEAR ANTI-DANDRUFF NUTRIUM', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-066', 66, 'CLINIC PLUS EGG', 'CLINIC PLUS EGG', 'Clinic Plus', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-067', 67, 'Clinic Plus STRONG&LONG', 'Clinic Plus STRONG&LONG', 'Clinic Plus', 'personal-care', NULL, 'Bag', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-068', 68, 'CLOTH PINS', 'CLOTH PINS', NULL, 'household', NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-069', 69, 'COCA CALA', 'COCA CALA', 'Coca-Cola', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-070', 70, 'Coconut', 'Coconut', NULL, 'fruits-vegetables', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-071', 71, 'COLGATE 100G', 'COLGATE 100G', 'Colgate', 'personal-care', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-072', 72, 'Colgate Brash', 'Colgate Brash', 'Colgate', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-073', 73, 'Colgate Brush Set', 'Colgate Brush Set', 'Colgate', 'household', 'Brush Set', 'Number', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-074', 74, 'COLGATE EXTRA MEDIUM', 'COLGATE EXTRA MEDIUM', 'Colgate', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-075', 75, 'COLGATE MAXFESH', 'COLGATE MAXFESH', 'Colgate', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-076', 76, 'Colgate Softb Kids', 'Colgate Softb Kids', 'Colgate', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-077', 77, 'Colgate Strong Teeth 300g', 'Colgate Strong Teeth 300g', 'Colgate', 'personal-care', '300g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-078', 78, 'COLGATE VEDSHIAIKTI 100G', 'COLGATE VEDSHIAIKTI 100G', 'Colgate', 'personal-care', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-079', 79, 'COLOUR PAPAD 250G', 'COLOUR PAPAD 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-080', 80, 'Comfort 30ml', 'Comfort 30ml', 'Comfort', NULL, '30ml', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-081', 81, 'Comfort Morning Fresh 210 Ml', 'Comfort Morning Fresh 210 Ml', 'Comfort', NULL, '210 Ml', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-082', 82, 'COMFORT ROYAL 80ML', 'COMFORT ROYAL 80ML', 'Comfort', NULL, '80ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-083', 83, 'CORIANDER 100G', 'CORIANDER 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-084', 84, 'CORIANDER POWDER 100G', 'CORIANDER POWDER 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-085', 85, 'CORIANDER POWDER 50G', 'CORIANDER POWDER 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-086', 86, 'CORIANDER SEEDS 250G', 'CORIANDER SEEDS 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-087', 87, 'CURD', 'CURD', NULL, 'dairy-bakery', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-088', 88, 'DABUR RED 100G', 'DABUR RED 100G', 'Dabur', 'personal-care', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-089', 89, 'DABUR RED 300G', 'DABUR RED 300G', 'Dabur', 'personal-care', '300G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-090', 90, 'DABUR RED 50G', 'DABUR RED 50G', 'Dabur', 'personal-care', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-091', 91, 'DAIRY MILK 10RS', 'DAIRY MILK 10RS', 'Dairy Milk', 'dairy-bakery', '10RS', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-092', 92, 'DAIRY MILK 5RS', 'DAIRY MILK 5RS', 'Dairy Milk', 'dairy-bakery', '5RS', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-093', 93, 'DARK FANTASY', 'DARK FANTASY', 'Dark Fantasy', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-094', 94, 'DARK FANTASY BOURBON 90G', 'DARK FANTASY BOURBON 90G', 'Bourbon', 'snacks', '90G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-095', 95, 'Dark Fantasy Choco Fills 10g', 'Dark Fantasy Choco Fills 10g', 'Dark Fantasy', 'snacks', '10g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-096', 96, 'DARK FANTASY CHOCOLATE COOKIE', 'DARK FANTASY CHOCOLATE COOKIE', 'Dark Fantasy', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-097', 97, 'Dark Fantasy Cookis', 'Dark Fantasy Cookis', 'Dark Fantasy', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-098', 98, 'DARK FANTASY VANILLA 55G', 'DARK FANTASY VANILLA 55G', 'Dark Fantasy', 'snacks', '55G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-099', 99, 'DARK FANTASY5RS', 'DARK FANTASY5RS', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-100', 100, 'DESI POPZ', 'DESI POPZ', NULL, 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-101', 101, 'DETTAL 250 ML', 'DETTAL 250 ML', 'Dettol', NULL, '250 ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-102', 102, 'DOMEX POWDER', 'DOMEX POWDER', 'Domex', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-103', 103, 'DOVE HAIR SHAMPOO6ML', 'DOVE HAIR SHAMPOO6ML', 'Dove', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-104', 104, 'DOVE SHAMPOO', 'DOVE SHAMPOO', 'Dove', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-105', 105, 'DOVE SOP BAR', 'DOVE SOP BAR', 'Dove', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-106', 106, 'DRY NUTS BOL', 'DRY NUTS BOL', NULL, 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-107', 107, 'DUSTPAN', 'DUSTPAN', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-108', 108, 'E BUTES', 'E BUTES', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-109', 109, 'EAGLE SAMBRANI 50G', 'EAGLE SAMBRANI 50G', 'Eagle', 'household', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-110', 110, 'Ear Buts', 'Ear Buts', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-111', 111, 'Eggs', 'Eggs', NULL, 'dairy-bakery', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-112', 112, 'EGGS TRA', 'EGGS TRA', NULL, 'dairy-bakery', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-113', 113, 'ELACHI', 'ELACHI', NULL, 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-114', 114, 'ELAICHI 10G', 'ELAICHI 10G', NULL, 'rice-dal-atta', '10G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-115', 115, 'ELAICHI RUSK 182G', 'ELAICHI RUSK 182G', NULL, 'dairy-bakery', '182G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-116', 116, 'ELAICHI RUSK 58G', 'ELAICHI RUSK 58G', NULL, 'dairy-bakery', '58G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-117', 117, 'ENDU MERCHI 250G', 'ENDU MERCHI 250G', NULL, 'rice-dal-atta', '250G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-118', 118, 'ENDU MERCHI 500G', 'ENDU MERCHI 500G', NULL, 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-119', 119, 'ENO', 'ENO', 'Eno', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-120', 120, 'EXO', 'EXO', 'Exo', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-121', 121, 'Exo 10', 'Exo 10', 'Exo', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-122', 122, 'Exo 5', 'Exo 5', 'Exo', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-123', 123, 'EXO POWDER 5600G', 'EXO POWDER 5600G', 'Exo', 'household', '5600G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-124', 124, 'EXO SCRUBRS', 'EXO SCRUBRS', 'Exo', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-125', 125, 'FAB LIQ 825G', 'FAB LIQ 825G', 'Fab', NULL, '825G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-126', 126, 'FAB LIQUID 10', 'FAB LIQUID 10', 'Fab', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-127', 127, 'FAIR LOVELI RE NEW 2.78G', 'FAIR LOVELI RE NEW 2.78G', 'Glow & Lovely', 'personal-care', '2.78G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-128', 128, 'FANTA 10RUPEES', 'FANTA 10RUPEES', 'Fanta', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-129', 129, 'FINGER MILLET 500G', 'FINGER MILLET 500G', NULL, NULL, '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-130', 130, 'FLAIR CARBONIX0.7MM', 'FLAIR CARBONIX0.7MM', 'Flair', NULL, '7MM', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-131', 131, 'FLATTENED RICE 250G', 'FLATTENED RICE 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-132', 132, 'FLATTENED RICE 500G', 'FLATTENED RICE 500G', NULL, 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-133', 133, 'FOGG SPRAY', 'FOGG SPRAY', 'Fogg', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-134', 134, 'Freedam Oil 500ml', 'Freedam Oil 500ml', 'Freedom', 'rice-dal-atta', '500ml', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-135', 135, 'Freedom 1LT', 'Freedom 1LT', 'Freedom', 'rice-dal-atta', '1LT', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-136', 136, 'FREEDOM GROUNDNUT OLI 1L', 'FREEDOM GROUNDNUT OLI 1L', 'Freedom', 'rice-dal-atta', '1L', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-137', 137, 'FREEDOM OIL 1L', 'FREEDOM OIL 1L', 'Freedom', 'rice-dal-atta', '1L', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-138', 138, 'FREEDOM RICE 1L', 'FREEDOM RICE 1L', 'Freedom', 'rice-dal-atta', '1L', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-139', 139, 'Fried Rice Masala 20g', 'Fried Rice Masala 20g', NULL, 'rice-dal-atta', '20g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-140', 140, 'Gadda Camphpr 25g', 'Gadda Camphpr 25g', NULL, 'household', '25g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-141', 141, 'GANGI PENDI 100G', 'GANGI PENDI 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-142', 142, 'GARLIC MIXTURE 100G', 'GARLIC MIXTURE 100G', NULL, 'snacks', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-143', 143, 'GARNIER F . W', 'GARNIER F . W', 'Garnier', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-144', 144, 'GAYATHARI SAMBRANI STICK', 'GAYATHARI SAMBRANI STICK', 'Gayathri', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-145', 145, 'Gelakara 50g', 'Gelakara 50g', NULL, 'rice-dal-atta', '50g', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-146', 146, 'GEMINI TEE 100G', 'GEMINI TEE 100G', 'Gemini', 'beverages', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-147', 147, 'Gilakara 100g', 'Gilakara 100g', NULL, 'rice-dal-atta', '100g', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-148', 148, 'Gkl Black Dates', 'Gkl Black Dates', NULL, 'rice-dal-atta', NULL, 'Pouches', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-149', 149, 'GKL SEEDED 250G', 'GKL SEEDED 250G', NULL, NULL, '250G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-150', 150, 'GLOW & LOVELY', 'GLOW & LOVELY', 'Glow & Lovely', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-151', 151, 'Glow&lovely 20g', 'Glow&lovely 20g', 'Glow & Lovely', 'personal-care', '20g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-152', 152, 'GN GOLD LIQ', 'GN GOLD LIQ', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-153', 153, 'GN GOLD MATCH', 'GN GOLD MATCH', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-154', 154, 'GOKILAM DATES 250G', 'GOKILAM DATES 250G', 'Gokulam', 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-155', 155, 'GOKUL SANTOL POWDER 30G', 'GOKUL SANTOL POWDER 30G', 'Gokul', 'personal-care', '30G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-156', 156, 'Gokulam Dates', 'Gokulam Dates', 'Gokulam', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-157', 157, 'GONGURA PICKELS 60G', 'GONGURA PICKELS 60G', NULL, 'rice-dal-atta', '60G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-158', 158, 'Gopuram', 'Gopuram', 'Gopuram', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-159', 159, 'GOPURAM 20G', 'GOPURAM 20G', 'Gopuram', 'rice-dal-atta', '20G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-160', 160, 'Gopuram Turmeric Powder 20g', 'Gopuram Turmeric Powder 20g', 'Gopuram', 'rice-dal-atta', '20g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-161', 161, 'Gopuram Turmeric Powder 50', 'Gopuram Turmeric Powder 50', 'Gopuram', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-162', 162, 'GRB GHEE', 'GRB GHEE', 'GRB', 'dairy-bakery', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-163', 163, 'GRB GHEE50ML', 'GRB GHEE50ML', 'GRB', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-164', 164, 'GULAB JAM (1+1) 160GM', 'GULAB JAM (1+1) 160GM', NULL, 'snacks', '160GM', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-165', 165, 'GULAB JAMUM MIX', 'GULAB JAMUM MIX', NULL, 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-166', 166, 'GUM 5RS', 'GUM 5RS', NULL, NULL, '5RS', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-167', 167, 'Harpic Blue 600m', 'Harpic Blue 600m', 'Harpic', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-168', 168, 'Harpic Red 500ml', 'Harpic Red 500ml', 'Harpic', 'household', '500ml', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-169', 169, 'HATSUN CURD', 'HATSUN CURD', 'Hatsun', 'dairy-bakery', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-170', 170, 'HEAD AND SHOULDER 2RS', 'HEAD AND SHOULDER 2RS', 'Head & Shoulders', NULL, '2RS', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-171', 171, 'HIDE&SEEK BISCUITS 10RS', 'HIDE&SEEK BISCUITS 10RS', 'Hide & Seek', 'snacks', '10RS', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-172', 172, 'HORLICKS', 'HORLICKS', 'Horlicks', 'beverages', NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-173', 173, 'Horlicks 500g', 'Horlicks 500g', 'Horlicks', 'beverages', '500g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-174', 174, 'Horlicks Biscuit Small', 'Horlicks Biscuit Small', 'Horlicks', 'beverages', NULL, 'Number', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-175', 175, 'Horlicks Biscuits', 'Horlicks Biscuits', 'Horlicks', 'beverages', NULL, 'Number', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-176', 176, 'HORLICKS BISCUITS', 'HORLICKS BISCUITS', 'Horlicks', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-177', 177, 'HR CHEKARALU 150G', 'HR CHEKARALU 150G', 'Haldiram''s', 'snacks', '150G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-178', 178, 'HR CORN FLAKES MIXTURE 24G', 'HR CORN FLAKES MIXTURE 24G', 'Haldiram''s', 'snacks', '24G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-179', 179, 'HR KHATTA MEETHA 48G', 'HR KHATTA MEETHA 48G', 'Haldiram''s', 'snacks', '48G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-180', 180, 'HR MASALA PEANUTS 34G', 'HR MASALA PEANUTS 34G', 'Haldiram''s', 'rice-dal-atta', '34G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-181', 181, 'HR MOONG DAL 200G', 'HR MOONG DAL 200G', 'Haldiram''s', 'rice-dal-atta', '200G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-182', 182, 'HR MOONG DAL 35G', 'HR MOONG DAL 35G', 'Haldiram''s', 'rice-dal-atta', '35G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-183', 183, 'HR SOYA CHIPS 42G', 'HR SOYA CHIPS 42G', 'Haldiram''s', 'snacks', '42G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-184', 184, 'HR TASTY NUTS 38G', 'HR TASTY NUTS 38G', 'Haldiram''s', 'snacks', '38G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-185', 185, 'IMMUNITY BOOSTING', 'IMMUNITY BOOSTING', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-186', 186, 'INDIA GATE 1KG', 'INDIA GATE 1KG', 'India Gate', 'rice-dal-atta', '1KG', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-187', 187, 'ITC CHIKKIN MASALA 50G', 'ITC CHIKKIN MASALA 50G', 'ITC', 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-188', 188, 'ITC GARAM MASALA 50G', 'ITC GARAM MASALA 50G', 'ITC', 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-189', 189, 'JAGGERY 1KG', 'JAGGERY 1KG', NULL, 'rice-dal-atta', '1KG', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-190', 190, 'JAGGERY 500G', 'JAGGERY 500G', NULL, 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-191', 191, 'JAM OJAM', 'JAM OJAM', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-192', 192, 'Jeedi Pappu 100g', 'Jeedi Pappu 100g', NULL, 'rice-dal-atta', '100g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-193', 193, 'Jeedi Pappu 250g', 'Jeedi Pappu 250g', NULL, 'rice-dal-atta', '250g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-194', 194, 'Jeedi Pappu 50g', 'Jeedi Pappu 50g', NULL, 'rice-dal-atta', '50g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-195', 195, 'JEERA 100G', 'JEERA 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-196', 196, 'JEERA 250G', 'JEERA 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-197', 197, 'JEERA 50G', 'JEERA 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-198', 198, 'JS OILE 800ML', 'JS OILE 800ML', NULL, 'rice-dal-atta', '800ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-199', 199, 'JS OILE DEEPAM 400ML', 'JS OILE DEEPAM 400ML', NULL, 'rice-dal-atta', '400ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-200', 200, 'JS OILS 180ML', 'JS OILS 180ML', NULL, 'rice-dal-atta', '180ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-201', 201, 'KALKANDA CANDY 250G', 'KALKANDA CANDY 250G', NULL, 'snacks', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-202', 202, 'Kandipappu 1kg', 'Kandipappu 1kg', NULL, 'rice-dal-atta', '1kg', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-203', 203, 'Kandipappu 500g', 'Kandipappu 500g', NULL, 'rice-dal-atta', '500g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-204', 204, 'KASTURI APPALAM 40G', 'KASTURI APPALAM 40G', NULL, 'rice-dal-atta', '40G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-205', 205, 'KASURI METHI 10G', 'KASURI METHI 10G', NULL, NULL, '10G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-206', 206, 'KINDAR JOYS 25', 'KINDAR JOYS 25', 'Kinder Joy', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-207', 207, 'KINDER JOY (B)', 'KINDER JOY (B)', 'Kinder Joy', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-208', 208, 'KINLEY 500ML', 'KINLEY 500ML', 'Kinley', 'beverages', '500ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-209', 209, 'KINLEY SALTY LEMON SODA', 'KINLEY SALTY LEMON SODA', 'Kinley', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-210', 210, 'KINLEYSTRONG SODA', 'KINLEYSTRONG SODA', NULL, 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-211', 211, 'KISAN JAM', 'KISAN JAM', 'Kissan', NULL, NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-212', 212, 'KISAN TOMOTA KETCHUP', 'KISAN TOMOTA KETCHUP', 'Kissan', NULL, NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-213', 213, 'KISMIS 100G', 'KISMIS 100G', NULL, 'rice-dal-atta', '100G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-214', 214, 'KISMIS 50G', 'KISMIS 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-215', 215, 'KITKAT', 'KITKAT', 'KitKat', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-216', 216, 'KNORR CUP SOUP', 'KNORR CUP SOUP', 'Knorr', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-217', 217, 'KNORR DARK SOYA SAS', 'KNORR DARK SOYA SAS', 'Knorr', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-218', 218, 'KNORR RED CHILLI SAUCE 200G', 'KNORR RED CHILLI SAUCE 200G', 'Knorr', NULL, '200G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-219', 219, 'KURNOOL RIC BAG 25KG', 'KURNOOL RIC BAG 25KG', NULL, 'rice-dal-atta', '25KG', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-220', 220, 'Lakme 2in1', 'Lakme 2in1', 'Lakme', 'personal-care', '2in1', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-221', 221, 'Lalitha Idly Ravva 1kg', 'Lalitha Idly Ravva 1kg', 'Lalitha', 'rice-dal-atta', '1kg', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-222', 222, 'Launch Plate', 'Launch Plate', NULL, NULL, NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-223', 223, 'LAVENDER', 'LAVENDER', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-224', 224, 'LG ENGIVA 50G', 'LG ENGIVA 50G', 'LG', 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-225', 225, 'LGV 10G', 'LGV 10G', 'LG', 'rice-dal-atta', '10G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-226', 226, 'LIMCA 10RUPEES', 'LIMCA 10RUPEES', 'Limca', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-227', 227, 'LION HONEY 250G', 'LION HONEY 250G', 'Lion', 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-228', 228, 'LION HONEY SET 250G', 'LION HONEY SET 250G', 'Lion', 'rice-dal-atta', '250G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-229', 229, 'LIRIL LIMEN', 'LIRIL LIMEN', 'Liril', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-230', 230, 'LOTTE CHOCO PIE', 'LOTTE CHOCO PIE', 'Lotte', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-231', 231, 'LUX GLUTATHIONE', 'LUX GLUTATHIONE', 'Lux', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-232', 232, 'LUX ROSE SCENT 545G', 'LUX ROSE SCENT 545G', 'Lux', 'personal-care', '545G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-233', 233, 'MAAZA 250ML', 'MAAZA 250ML', 'Maaza', 'beverages', '250ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-234', 234, 'MAGGI 140G', 'MAGGI 140G', 'Maggi', 'snacks', '140G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-235', 235, 'MAGGI 15RS', 'MAGGI 15RS', 'Maggi', 'snacks', '15RS', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-236', 236, 'Makhana SeaSalt&pepper 70g', 'Makhana SeaSalt&pepper 70g', NULL, 'rice-dal-atta', '70g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-237', 237, 'MALKIST', 'MALKIST', 'Malkist', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-238', 238, 'MALKIST CHEESE 144G', 'MALKIST CHEESE 144G', 'Malkist', 'snacks', '144G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-239', 239, 'MALKIST CHEESE 72G', 'MALKIST CHEESE 72G', 'Malkist', 'snacks', '72G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-240', 240, 'MALKIST DOUBLE CHOCOLATEY 144G', 'MALKIST DOUBLE CHOCOLATEY 144G', 'Malkist', 'snacks', '144G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-241', 241, 'MALKIST DOUBLE CHOCOLATEY 72G', 'MALKIST DOUBLE CHOCOLATEY 72G', 'Malkist', 'snacks', '72G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-242', 242, 'MANGALDEEP 3IN1', 'MANGALDEEP 3IN1', 'Mangaldeep', NULL, '3IN1', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-243', 243, 'MANGALDEEP FLORA', 'MANGALDEEP FLORA', 'Mangaldeep', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-244', 244, 'Mangaldeep Sambrani', 'Mangaldeep Sambrani', 'Mangaldeep', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-245', 245, 'Mangaldeep Samrani Cup 1 Box', 'Mangaldeep Samrani Cup 1 Box', 'Mangaldeep', 'household', '1 Box', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-246', 246, 'MANGALDEEP SCENT 110G', 'MANGALDEEP SCENT 110G', 'Mangaldeep', NULL, '110G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-247', 247, 'Mangaldeep Treya', 'Mangaldeep Treya', 'Mangaldeep', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-248', 248, 'MANGO FRUIT', 'MANGO FRUIT', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-249', 249, 'MARGO ORIGINAL 500G', 'MARGO ORIGINAL 500G', 'Margo', NULL, '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-250', 250, 'MARIE LIGHT ACTIVE 140G', 'MARIE LIGHT ACTIVE 140G', 'Marie Light', NULL, '140G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-251', 251, 'MARIE LIGHT ACTIVE 34G', 'MARIE LIGHT ACTIVE 34G', 'Marie Light', NULL, '34G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-252', 252, 'Masala Noodles 200g', 'Masala Noodles 200g', NULL, 'rice-dal-atta', '200g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-253', 253, 'MAYA AGARBATHI', 'MAYA AGARBATHI', 'Maya', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-254', 254, 'MEDIMIX CLASSIC SOP 75G', 'MEDIMIX CLASSIC SOP 75G', 'Medimix', 'personal-care', '75G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-255', 255, 'MENTHULU 100G', 'MENTHULU 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-256', 256, 'MENTHULU 250G', 'MENTHULU 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-257', 257, 'MENTHULU 50G', 'MENTHULU 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-258', 258, 'MIKL RUSK 58G', 'MIKL RUSK 58G', NULL, 'dairy-bakery', '58G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-259', 259, 'MILK BIKIS', 'MILK BIKIS', 'Milk Bikis', 'dairy-bakery', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-260', 260, 'MILK RUSK 182G', 'MILK RUSK 182G', NULL, 'dairy-bakery', '182G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-261', 261, 'MILKYBAR', 'MILKYBAR', 'Milkybar', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-262', 262, 'MILKYBAR CHOO', 'MILKYBAR CHOO', 'Milkybar', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-263', 263, 'MILKYBBAR SMAL BOX', 'MILKYBBAR SMAL BOX', 'Milkybar', 'snacks', NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-264', 264, 'Minapappu 1kg', 'Minapappu 1kg', NULL, 'rice-dal-atta', '1kg', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-265', 265, 'Minapapu 500g', 'Minapapu 500g', NULL, 'rice-dal-atta', '500g', 'Number', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-266', 266, 'MINUTE MAID ORANGE', 'MINUTE MAID ORANGE', 'Minute Maid', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-267', 267, 'MIRIYALU 50G', 'MIRIYALU 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-268', 268, 'MOMS MAGIC CASHEW& ALMOND', 'MOMS MAGIC CASHEW& ALMOND', 'Mom''s Magic', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-269', 269, 'MOMS MAGIC CASHEW&ALMOND 61G', 'MOMS MAGIC CASHEW&ALMOND 61G', 'Mom''s Magic', 'rice-dal-atta', '61G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-270', 270, 'MOMS MAGIC SHINES SHINIG BUTTER 126G', 'MOMS MAGIC SHINES SHINIG BUTTER 126G', 'Mom''s Magic', NULL, '126G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-271', 271, 'MOMS MAGIC SHINES SHINING BUTTER 44G', 'MOMS MAGIC SHINES SHINING BUTTER 44G', 'Mom''s Magic', NULL, '44G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-272', 272, 'MOON DAL 250G', 'MOON DAL 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-273', 273, 'MOON DAL 500G', 'MOON DAL 500G', NULL, 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-274', 274, 'MOONG DALL 120G', 'MOONG DALL 120G', NULL, 'rice-dal-atta', '120G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-275', 275, 'MROW', 'MROW', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-276', 276, 'MUNCH 5RS', 'MUNCH 5RS', 'Munch', 'snacks', '5RS', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-277', 277, 'MUNG BEAN 500G', 'MUNG BEAN 500G', NULL, NULL, '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-278', 278, 'MURALI VATHULU', 'MURALI VATHULU', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-279', 279, 'Muskmelon Seeds 100g', 'Muskmelon Seeds 100g', NULL, 'rice-dal-atta', '100g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-280', 280, 'MYSORE SANDAL 50G', 'MYSORE SANDAL 50G', 'Mysore Sandal', NULL, '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-281', 281, 'Mysore Sandal Gold', 'Mysore Sandal Gold', 'Mysore Sandal', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-282', 282, 'MYSORE SANDAL SOAP 150G', 'MYSORE SANDAL SOAP 150G', 'Mysore Sandal', 'personal-care', '150G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-283', 283, 'MYSORE SANDAL SOP 125G', 'MYSORE SANDAL SOP 125G', 'Mysore Sandal', 'personal-care', '125G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-284', 284, 'MYSORE SANDALS FRESHNOL', 'MYSORE SANDALS FRESHNOL', 'Mysore Sandal', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-285', 285, 'NALLA KARAM PODI 150G', 'NALLA KARAM PODI 150G', NULL, 'rice-dal-atta', '150G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-286', 286, 'NATURO', 'NATURO', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-287', 287, 'NAVARATNA OIL 50ML', 'NAVARATNA OIL 50ML', 'Navaratna', 'personal-care', '50ML', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-288', 288, 'NEEM NIMYLE 200ML', 'NEEM NIMYLE 200ML', 'Nimyle', 'household', '200ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-289', 289, 'Nice Peanut Chikki', 'Nice Peanut Chikki', NULL, 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-290', 290, 'NO 1 SOAP LEMON', 'NO 1 SOAP LEMON', NULL, 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-291', 291, 'NSR', 'NSR', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-292', 292, 'NUVVULU 250G', 'NUVVULU 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-293', 293, 'NYCIL GERM EXPERT 210G', 'NYCIL GERM EXPERT 210G', 'Nycil', 'personal-care', '210G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-294', 294, 'NYCIL POWDER SMALL', 'NYCIL POWDER SMALL', 'Nycil', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-295', 295, 'OATS 400G', 'OATS 400G', NULL, NULL, '400G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-296', 296, 'OIONES 500G', 'OIONES 500G', NULL, 'fruits-vegetables', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-297', 297, 'ONIONS 1KG', 'ONIONS 1KG', NULL, 'fruits-vegetables', '1KG', 'Bag', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-298', 298, 'ORINGE CANDY 150G', 'ORINGE CANDY 150G', NULL, 'snacks', '150G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-299', 299, 'Osmania Bisc', 'Osmania Bisc', NULL, 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-300', 300, 'Pachisenaga Pappu 250g', 'Pachisenaga Pappu 250g', NULL, 'rice-dal-atta', '250g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-301', 301, 'Pachisenagapappu 500g', 'Pachisenagapappu 500g', NULL, NULL, '500g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-302', 302, 'PARACHUTE 175ML', 'PARACHUTE 175ML', 'Parachute', NULL, '175ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-303', 303, 'Parachute Aloe Vera 250ml', 'Parachute Aloe Vera 250ml', 'Parachute', NULL, '250ml', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-304', 304, 'PARACHUTEB 100ML', 'PARACHUTEB 100ML', 'Parachute', NULL, '100ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-305', 305, 'PARK10RS', 'PARK10RS', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-306', 306, 'PEARS PURE& GENTLE GLOW 52G', 'PEARS PURE& GENTLE GLOW 52G', 'Pears', 'personal-care', '52G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-307', 307, 'PEARS WITH MINT 50G', 'PEARS WITH MINT 50G', 'Pears', 'personal-care', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-308', 308, 'Pepper 100g', 'Pepper 100g', NULL, 'rice-dal-atta', '100g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-309', 309, 'PEPPER BOLS 50G', 'PEPPER BOLS 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-310', 310, 'PITAMBARI 20G', 'PITAMBARI 20G', 'Pitambari', 'household', '20G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-311', 311, 'POND S 23G', 'POND S 23G', 'Pond''s', 'personal-care', '23G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-312', 312, 'PONDS BRICHT BEAUTY 15G', 'PONDS BRICHT BEAUTY 15G', 'Pond''s', 'personal-care', '15G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-313', 313, 'Ponds Cold Cream', 'Ponds Cold Cream', 'Pond''s', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-314', 314, 'POOJA GOLD OIL 800ML', 'POOJA GOLD OIL 800ML', NULL, 'rice-dal-atta', '800ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-315', 315, 'POOJA OIAL 800ML', 'POOJA OIAL 800ML', NULL, NULL, '800ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-316', 316, 'POOJA POWDER 50 G,', 'POOJA POWDER 50 G,', NULL, NULL, '50 G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-317', 317, 'POOJA POWDER B GANDAM', 'POOJA POWDER B GANDAM', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-318', 318, 'POWER NATURAL SOAP', 'POWER NATURAL SOAP', NULL, 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-319', 319, 'Priya Gold 500g', 'Priya Gold 500g', 'Priya', NULL, '500g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-320', 320, 'PRIYA GOLD1KG', 'PRIYA GOLD1KG', 'Priya', NULL, NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-321', 321, 'Pumpkin Seeds 100g', 'Pumpkin Seeds 100g', NULL, 'rice-dal-atta', '100g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-322', 322, 'REAL AAM 400G', 'REAL AAM 400G', NULL, NULL, '400G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-323', 323, 'RED CHILLI PICKEL 60G', 'RED CHILLI PICKEL 60G', NULL, NULL, '60G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-324', 324, 'RED LABUL NATURAL 100G', 'RED LABUL NATURAL 100G', 'Red Label', NULL, '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-325', 325, 'RED LENTILS 500G', 'RED LENTILS 500G', NULL, NULL, '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-326', 326, 'RIMZIM JEERA', 'RIMZIM JEERA', NULL, 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-327', 327, 'RIN', 'RIN', 'Rin', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-328', 328, 'RIN ANTIBAV', 'RIN ANTIBAV', 'Rin', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-329', 329, 'RIN MATIC', 'RIN MATIC', 'Rin', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-330', 330, 'ROBAN CAKE 25G', 'ROBAN CAKE 25G', NULL, 'snacks', '25G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-331', 331, 'RUCHI GOLD 750G', 'RUCHI GOLD 750G', 'Ruchi Gold', NULL, '750G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-332', 332, 'Ruchigold 1kg', 'Ruchigold 1kg', 'Ruchi Gold', NULL, '1kg', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-333', 333, 'SAGGUBIYYAM 250G', 'SAGGUBIYYAM 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-334', 334, 'SAI BANSI RAVVA 500G', 'SAI BANSI RAVVA 500G', NULL, 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-335', 335, 'SALT MIRCHI 250G', 'SALT MIRCHI 250G', NULL, 'rice-dal-atta', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-336', 336, 'SANTOOR', 'SANTOOR', 'Santoor', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-337', 337, 'SANTOOR 150G', 'SANTOOR 150G', 'Santoor', 'personal-care', '150G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-338', 338, 'SANTOOR FRESH SKIN', 'SANTOOR FRESH SKIN', 'Santoor', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-339', 339, 'SANTOOR SOAP BIG SET', 'SANTOOR SOAP BIG SET', 'Santoor', 'personal-care', 'BIG SET', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-340', 340, 'Savlon Handwash 375 Ml', 'Savlon Handwash 375 Ml', 'Savlon', 'personal-care', '375 Ml', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-341', 341, 'SCISSORS 10INCH', 'SCISSORS 10INCH', NULL, NULL, '10INCH', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-342', 342, 'Sensodyne Bresh', 'Sensodyne Bresh', 'Sensodyne', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-343', 343, 'SENSORA PASTE 80G', 'SENSORA PASTE 80G', 'Sensora', 'personal-care', '80G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-344', 344, 'SHINK BRASHS', 'SHINK BRASHS', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-345', 345, 'SMART MOP', 'SMART MOP', NULL, 'household', NULL, 'Pairs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-346', 346, 'SOANPAPDI', 'SOANPAPDI', NULL, 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-347', 347, 'SOLO FRESH 100G', 'SOLO FRESH 100G', NULL, NULL, '100G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-348', 348, 'SOMPU 50G', 'SOMPU 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-349', 349, 'SOMPU100G', 'SOMPU100G', NULL, NULL, NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-350', 350, 'SORGHUM500G', 'SORGHUM500G', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-351', 351, 'SOYA BIG 100G', 'SOYA BIG 100G', NULL, NULL, '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-352', 352, 'SOYA CHUNKS 42G', 'SOYA CHUNKS 42G', NULL, NULL, '42G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-353', 353, 'SOYA SMALL 100G', 'SOYA SMALL 100G', NULL, NULL, '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-354', 354, 'SOYA SMALL 50G', 'SOYA SMALL 50G', NULL, NULL, '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-355', 355, 'SP CHOCOLATE 200G', 'SP CHOCOLATE 200G', NULL, 'snacks', '200G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-356', 356, 'SP DUET 200G', 'SP DUET 200G', NULL, NULL, '200G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-357', 357, 'SPINZ BB FACE POWDER 10G', 'SPINZ BB FACE POWDER 10G', 'Spinz', 'personal-care', '10G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-358', 358, 'SPINZ BBCREAM15G', 'SPINZ BBCREAM15G', 'Spinz', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-359', 359, 'SPINZ BBPOWDER20G', 'SPINZ BBPOWDER20G', 'Spinz', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-360', 360, 'SPRITE 1L', 'SPRITE 1L', 'Sprite', 'beverages', '1L', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-361', 361, 'SRI DURGA CHILLI POWDER 100G', 'SRI DURGA CHILLI POWDER 100G', 'Sri Durga', NULL, '100G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-362', 362, 'SRI DURGA CORIANDER 100G', 'SRI DURGA CORIANDER 100G', 'Sri Durga', 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-363', 363, 'SRI DURGA DANIA POWDER 50G', 'SRI DURGA DANIA POWDER 50G', 'Sri Durga', NULL, '50G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-364', 364, 'Sri Durga Green Tamarind Pickleb 200g', 'Sri Durga Green Tamarind Pickleb 200g', 'Sri Durga', 'rice-dal-atta', '200g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-365', 365, 'SRI DURGA MANGO AVAKAI 200G', 'SRI DURGA MANGO AVAKAI 200G', 'Sri Durga', NULL, '200G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-366', 366, 'SRI DURGA PAPULA PODI150G', 'SRI DURGA PAPULA PODI150G', 'Sri Durga', NULL, NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-367', 367, 'SRI DURGA SINGER GARLIC', 'SRI DURGA SINGER GARLIC', 'Sri Durga', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-368', 368, 'SRI DURGA TARMARIK 50G', 'SRI DURGA TARMARIK 50G', 'Sri Durga', 'rice-dal-atta', '50G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-369', 369, 'SRI DURGA TOMATO PICKLE 200G', 'SRI DURGA TOMATO PICKLE 200G', 'Sri Durga', 'rice-dal-atta', '200G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-370', 370, 'SRI DURGA TOMATO PICKLE 500G', 'SRI DURGA TOMATO PICKLE 500G', 'Sri Durga', 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-371', 371, 'SRI PAPADS 100G', 'SRI PAPADS 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-372', 372, 'SS ROD', 'SS ROD', NULL, NULL, NULL, 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-373', 373, 'SSCG3', 'SSCG3', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-374', 374, 'SSCG4S', 'SSCG4S', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-375', 375, 'STARFREE XL', 'STARFREE XL', NULL, 'personal-care', 'XL', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-376', 376, 'STRABERRY CANDYB 135G', 'STRABERRY CANDYB 135G', NULL, 'snacks', '135G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-377', 377, 'Subha Lakshmi Turmeric 100', 'Subha Lakshmi Turmeric 100', NULL, 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-378', 378, 'Sugar 1Kg', 'Sugar 1Kg', NULL, 'rice-dal-atta', '1Kg', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-379', 379, 'Sugar 500g', 'Sugar 500g', NULL, 'rice-dal-atta', '500g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-380', 380, 'SUN GOLD SOAP 25', 'SUN GOLD SOAP 25', 'Sun Gold', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-381', 381, 'SUNFEAST BOUNCE 28G', 'SUNFEAST BOUNCE 28G', 'Sunfeast', NULL, '28G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-382', 382, 'SUNFEAST FANTASTIK CHOCO ALMOND', 'SUNFEAST FANTASTIK CHOCO ALMOND', 'Sunfeast', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-383', 383, 'SUNFEAST FANTASTIK FRUIT &NUT', 'SUNFEAST FANTASTIK FRUIT &NUT', 'Sunfeast', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-384', 384, 'SUNFEAST GLICOSE 24G', 'SUNFEAST GLICOSE 24G', 'Sunfeast', NULL, '24G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-385', 385, 'SUNFEAST SUPERMILK 31G', 'SUNFEAST SUPERMILK 31G', 'Sunfeast', NULL, '31G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-386', 386, 'SUNFEAST SUPERMILK 72G', 'SUNFEAST SUPERMILK 72G', 'Sunfeast', NULL, '72G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-387', 387, 'SUNFEAST SWEET&SALTY 68G', 'SUNFEAST SWEET&SALTY 68G', 'Sunfeast', NULL, '68G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-388', 388, 'Sunflower Seeds 100g', 'Sunflower Seeds 100g', NULL, 'rice-dal-atta', '100g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-389', 389, 'SUPER MOP', 'SUPER MOP', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-390', 390, 'SURF EXCEL 10', 'SURF EXCEL 10', 'Surf Excel', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-391', 391, 'SURF EXCEL 65G', 'SURF EXCEL 65G', 'Surf Excel', 'household', '65G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-392', 392, 'SURF EXCEL 84 G', 'SURF EXCEL 84 G', 'Surf Excel', 'household', '84 G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-393', 393, 'Surf Excel Bar 250g', 'Surf Excel Bar 250g', 'Surf Excel', 'household', '250g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-394', 394, 'SURF EXCEL MATIC 70G', 'SURF EXCEL MATIC 70G', 'Surf Excel', 'household', '70G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-395', 395, 'SURFEXEL SOPE', 'SURFEXEL SOPE', 'Surf Excel', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-396', 396, 'SURYA DEVA', 'SURYA DEVA', 'Surya Deva', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-397', 397, 'Swastiks Mango Pickle200g', 'Swastiks Mango Pickle200g', 'Swastiks', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-398', 398, 'SWASTIKS RED CHILLI PICKLE 500G', 'SWASTIKS RED CHILLI PICKLE 500G', 'Swastiks', 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-399', 399, 'SWD GARLIC MIXTUR', 'SWD GARLIC MIXTUR', NULL, 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-400', 400, 'SWD SPICY NUTS 25G', 'SWD SPICY NUTS 25G', NULL, NULL, '25G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-401', 401, 'SWEEPER', 'SWEEPER', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-402', 402, 'TAJ MAHAL 250G', 'TAJ MAHAL 250G', 'Taj Mahal', 'beverages', '250G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-403', 403, 'TAMARIND250G', 'TAMARIND250G', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-404', 404, 'TAMARIND500G', 'TAMARIND500G', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-405', 405, 'TANGY IMLI 350G', 'TANGY IMLI 350G', NULL, 'rice-dal-atta', '350G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-406', 406, 'TASTY NUTS 100G', 'TASTY NUTS 100G', NULL, 'snacks', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-407', 407, 'TATA RA SALT', 'TATA RA SALT', 'Tata', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-408', 408, 'Telagadalu 100G', 'Telagadalu 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-409', 409, 'Telagadalu 250G', 'Telagadalu 250G', NULL, 'rice-dal-atta', '250G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-410', 410, 'Telagadalu 500g', 'Telagadalu 500g', NULL, 'rice-dal-atta', '500g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-411', 411, 'TERMERIC POWDER 100G', 'TERMERIC POWDER 100G', NULL, 'rice-dal-atta', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-412', 412, 'TERMERIC POWDER 500G', 'TERMERIC POWDER 500G', NULL, 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-413', 413, 'TERMERIC POWDER 50G', 'TERMERIC POWDER 50G', NULL, 'rice-dal-atta', '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-414', 414, 'Thumsup', 'Thumsup', 'Thums Up', 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-415', 415, 'THUMSUP 1L', 'THUMSUP 1L', 'Thums Up', 'beverages', '1L', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-416', 416, 'THUMSUP 2.25L', 'THUMSUP 2.25L', 'Thums Up', 'beverages', '2.25L', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-417', 417, 'TOMATO SOUP', 'TOMATO SOUP', NULL, 'beverages', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-418', 418, 'TRESEMME 180ML', 'TRESEMME 180ML', 'Tresemme', 'personal-care', '180ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-419', 419, 'TULIPS COTTON SWABS', 'TULIPS COTTON SWABS', 'Tulips', 'personal-care', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-420', 420, 'UINIBIC CASEW BADAM', 'UINIBIC CASEW BADAM', 'Unibic', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-421', 421, 'UINIBIC CHOCO CHIP', 'UINIBIC CHOCO CHIP', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-422', 422, 'UINIBIC CHOCO RIPPLE', 'UINIBIC CHOCO RIPPLE', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-423', 423, 'UINIBIC ORANGE SPLASH', 'UINIBIC ORANGE SPLASH', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-424', 424, 'UJALA 30ML', 'UJALA 30ML', 'Ujala', NULL, '30ML', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-425', 425, 'Ujala 75ml', 'Ujala 75ml', 'Ujala', NULL, '75ml', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-426', 426, 'ULTIMATE POWER LIQUID DETERGENT', 'ULTIMATE POWER LIQUID DETERGENT', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-427', 427, 'ULTRA FLOOR CLEAN', 'ULTRA FLOOR CLEAN', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-428', 428, 'ULTRA SOFT BRUSH', 'ULTRA SOFT BRUSH', NULL, 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-429', 429, 'UNIBIC BUTTER', 'UNIBIC BUTTER', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-430', 430, 'UNIBIC CASHEW', 'UNIBIC CASHEW', 'Unibic', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-431', 431, 'UNIBIC CASHEW BADAM', 'UNIBIC CASHEW BADAM', 'Unibic', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-432', 432, 'UNIBIC CHOCO CHIP', 'UNIBIC CHOCO CHIP', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-433', 433, 'UNIBIC CHOCO NUT', 'UNIBIC CHOCO NUT', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-434', 434, 'UNIBIC CHOCO RIPPLE', 'UNIBIC CHOCO RIPPLE', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-435', 435, 'UNIBIC CHOCOLATE WAFER', 'UNIBIC CHOCOLATE WAFER', 'Unibic', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-436', 436, 'UNIBIC COCONUT', 'UNIBIC COCONUT', 'Unibic', 'fruits-vegetables', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-437', 437, 'UNIBIC DANISH COCONUT', 'UNIBIC DANISH COCONUT', 'Unibic', 'fruits-vegetables', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-438', 438, 'UNIBIC FRUIT & NUT', 'UNIBIC FRUIT & NUT', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-439', 439, 'UNIBIC OATS', 'UNIBIC OATS', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-440', 440, 'UNIBIC ORANGE SPLASH', 'UNIBIC ORANGE SPLASH', 'Unibic', NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-441', 441, 'UNIBIC PISTA BADAM', 'UNIBIC PISTA BADAM', 'Unibic', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-442', 442, 'UNIBIC RICH CHOCOLATE WAFER', 'UNIBIC RICH CHOCOLATE WAFER', 'Unibic', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-443', 443, 'UNIBIC STRABERRY WAFER', 'UNIBIC STRABERRY WAFER', 'Unibic', 'snacks', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-444', 444, 'VAM 50G', 'VAM 50G', NULL, NULL, '50G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-445', 445, 'VASELINE 5.5G', 'VASELINE 5.5G', 'Vaseline', 'personal-care', '5.5G', 'Packs', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-446', 446, 'Vermicilli Bambino1kg', 'Vermicilli Bambino1kg', NULL, 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-447', 447, 'Vermicilli Payasam Mix', 'Vermicilli Payasam Mix', NULL, 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-448', 448, 'Verusenaga Pappu 1kg', 'Verusenaga Pappu 1kg', NULL, 'rice-dal-atta', '1kg', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-449', 449, 'Verusenaga Pappu 500g', 'Verusenaga Pappu 500g', NULL, 'rice-dal-atta', '500g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-450', 450, 'VIJAYA GROUNDNUT OIL 1L', 'VIJAYA GROUNDNUT OIL 1L', 'Vijaya', 'rice-dal-atta', '1L', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-451', 451, 'Vim 10g', 'Vim 10g', 'Vim', 'household', '10g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-452', 452, 'Vim 126g', 'Vim 126g', 'Vim', 'household', '126g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-453', 453, 'VIM 190ML', 'VIM 190ML', 'Vim', 'household', '190ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-454', 454, 'VIM 250ML', 'VIM 250ML', 'Vim', 'household', '250ML', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-455', 455, 'Vim 480g', 'Vim 480g', 'Vim', 'household', '480g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-456', 456, 'Vim 5rs Bar', 'Vim 5rs Bar', 'Vim', 'household', '5rs', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-457', 457, 'Vim Sop', 'Vim Sop', 'Vim', 'household', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-458', 458, 'Vt Avalu 100g', 'Vt Avalu 100g', NULL, 'rice-dal-atta', '100g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-459', 459, 'WAGH BAKRI TEA 100G', 'WAGH BAKRI TEA 100G', 'Wagh Bakri', 'beverages', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-460', 460, 'WAGH BAKRI250G', 'WAGH BAKRI250G', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-461', 461, 'WAGHB BAKRI ELAICHI 100G', 'WAGHB BAKRI ELAICHI 100G', 'Wagh Bakri', 'beverages', '100G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-462', 462, 'WALL STICK', 'WALL STICK', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-463', 463, 'Watermelon Seeds 100g', 'Watermelon Seeds 100g', NULL, 'rice-dal-atta', '100g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-464', 464, 'WHISPER XXL', 'WHISPER XXL', 'Whisper', 'personal-care', 'XXL', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-465', 465, 'WHITE URAD DAL 500G', 'WHITE URAD DAL 500G', NULL, 'rice-dal-atta', '500G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-466', 466, 'WHITE URAD DAL250g', 'WHITE URAD DAL250g', NULL, 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-467', 467, 'WIPPER STICK', 'WIPPER STICK', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-468', 468, 'WOMENS PLUS', 'WOMENS PLUS', NULL, NULL, NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-469', 469, 'Yendu Kobbari 250g', 'Yendu Kobbari 250g', NULL, 'rice-dal-atta', '250g', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-470', 470, 'YIPPEE NOODLES 280G', 'YIPPEE NOODLES 280G', 'Yippee', 'snacks', '280G', 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-471', 471, 'YIPPEE NOODLES MAGIC MASALA', 'YIPPEE NOODLES MAGIC MASALA', 'Yippee', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true),
('g1-prod-472', 472, 'YIPPEE WOW MASALA', 'YIPPEE WOW MASALA', 'Yippee', 'rice-dal-atta', NULL, 'Pieces', NULL, NULL, NULL, 0, true, NULL, 'MISSING', NULL, 5.00, 0, false, false, true, true)
ON CONFLICT (id) DO UPDATE SET
  source_item_no = EXCLUDED.source_item_no,
  source_name = EXCLUDED.source_name,
  name = EXCLUDED.name,
  variant = EXCLUDED.variant,
  unit = EXCLUDED.unit,
  active = EXCLUDED.active,
  is_active = EXCLUDED.is_active,
  -- Do not overwrite verified product images
  image_url = CASE 
    WHEN public.products.image_status = 'VERIFIED' THEN public.products.image_url 
    ELSE EXCLUDED.image_url 
  END,
  image_status = CASE 
    WHEN public.products.image_status = 'VERIFIED' THEN 'VERIFIED' 
    ELSE EXCLUDED.image_status 
  END,
  -- Do not overwrite verified prices, stock, brand, or category if already populated
  brand = COALESCE(public.products.brand, EXCLUDED.brand),
  category_id = COALESCE(public.products.category_id, EXCLUDED.category_id),
  price = COALESCE(public.products.price, EXCLUDED.price),
  original_price = COALESCE(public.products.original_price, EXCLUDED.original_price),
  stock_count = COALESCE(public.products.stock_count, EXCLUDED.stock_count);
